/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5uU4LbmmcY9V8oBke7M62e
// Component: 0wdzzh1Ln_xG

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import { AntdDropdown } from "@plasmicpkgs/antd5/skinny/registerDropdown";
import { AntdMenuItem } from "@plasmicpkgs/antd5/skinny/registerMenu";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import Modal from "../../Modal"; // plasmic-import: 2mIwXeE-_Psc/component
import { AntdRate } from "@plasmicpkgs/antd5/skinny/registerRate";
import { AntdTextArea } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdTextArea_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import Button2 from "../../Button2"; // plasmic-import: t1SFzVEz5RlV/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 5uU4LbmmcY9V8oBke7M62e/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 5uU4LbmmcY9V8oBke7M62e/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 5uU4LbmmcY9V8oBke7M62e/projectcss
import sty from "./PlasmicARatingMembers.module.css"; // plasmic-import: 0wdzzh1Ln_xG/css

import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: 6guEK3lWtsZR/icon
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: y4E8J3i62sTp/icon
import IlustrgatuSvgIcon from "./icons/PlasmicIcon__IlustrgatuSvg"; // plasmic-import: 0rpJDt-WBeXQ/icon
import PoliteSvgIcon from "./icons/PlasmicIcon__PoliteSvg"; // plasmic-import: f0PNUwY-Sl9R/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: l4RREmL1A-vM/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: qJDdQLGS2RlC/icon
import SkillSvgIcon from "./icons/PlasmicIcon__SkillSvg"; // plasmic-import: 9JUauDy9mxmq/icon
import CustomerRatesSvgIcon from "./icons/PlasmicIcon__CustomerRatesSvg"; // plasmic-import: ayP013CUNl9_/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "Rating Members",

    openGraph: {
      title: "Rating Members"
    },
    twitter: {
      card: "summary" as const,
      title: "Rating Members"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicARatingMembers__VariantMembers = {};
export type PlasmicARatingMembers__VariantsArgs = {};
type VariantPropType = keyof PlasmicARatingMembers__VariantsArgs;
export const PlasmicARatingMembers__VariantProps = new Array<VariantPropType>();

export type PlasmicARatingMembers__ArgsType = {};
type ArgPropType = keyof PlasmicARatingMembers__ArgsType;
export const PlasmicARatingMembers__ArgProps = new Array<ArgPropType>();

export type PlasmicARatingMembers__OverridesType = {
  root?: Flex__<"div">;
  topBarAuto?: Flex__<"div">;
  navigationBar?: Flex__<typeof NavigationBar>;
  account2?: Flex__<typeof AntdDropdown>;
  button?: Flex__<typeof AntdButton>;
  container1?: Flex__<"div">;
  profilePic?: Flex__<typeof PlasmicImg__>;
  communityLogo?: Flex__<typeof PlasmicImg__>;
  firstName?: Flex__<"div">;
  lastName?: Flex__<"div">;
  age?: Flex__<"div">;
  location?: Flex__<"div">;
  charge?: Flex__<"div">;
  linkedIn?: Flex__<"a"> & Partial<LinkProps>;
  instagram?: Flex__<"a"> & Partial<LinkProps>;
  x?: Flex__<"a"> & Partial<LinkProps>;
  rateThisMember?: Flex__<"div">;
  rate?: Flex__<typeof Modal>;
  rating?: Flex__<typeof AntdRate>;
  comment?: Flex__<typeof AntdTextArea>;
  confirmRate?: Flex__<typeof Button2>;
  rate2?: Flex__<typeof Modal>;
  rateTechnical?: Flex__<typeof AntdRate>;
  comment2?: Flex__<typeof AntdTextArea>;
  confirmRate2?: Flex__<typeof Button2>;
  memberRated?: Flex__<typeof AntdRate>;
  reportRate?: Flex__<"div">;
  reportDate?: Flex__<"div">;
  ethics?: Flex__<typeof AntdRate>;
  technicalPerformance?: Flex__<typeof AntdRate>;
  memberRated2?: Flex__<typeof AntdRate>;
};

export interface DefaultARatingMembersProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicARatingMembers__RenderFunc(props: {
  variants: PlasmicARatingMembers__VariantsArgs;
  args: PlasmicARatingMembers__ArgsType;
  overrides: PlasmicARatingMembers__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "ethics.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "technicalPerformance.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "memberRated2.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "rate.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "rating.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "comment.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdTextArea_Helpers)
      },
      {
        path: "memberRated.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "rate2.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "rateTechnical.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "comment2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdTextArea_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"topBarAuto"}
            data-plasmic-override={overrides.topBarAuto}
            className={classNames(projectcss.all, sty.topBarAuto)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__i524M)}>
              <div className={classNames(projectcss.all, sty.freeBox___5M7Zn)}>
                <NavigationBar
                  data-plasmic-name={"navigationBar"}
                  data-plasmic-override={overrides.navigationBar}
                  brand={
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__dWq6J
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___6S5Ud)}
                        displayHeight={"30px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={{
                          src: "/plasmic/ez_marketing_platform_sacanagem/images/ezSvg2.svg",
                          fullWidth: 60,
                          fullHeight: 31,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                  }
                  className={classNames("__wab_instance", sty.navigationBar)}
                  closeButton={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__oVm93)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      src={"https://static1.plasmic.app/close.svg"}
                    />
                  }
                  itemsGap={8}
                  menuItems={
                    <React.Fragment>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__lCy56
                        )}
                        component={Link}
                        href={`/a-community-dashboard`}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        {"Community Dashboard"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__npsrp
                        )}
                        component={Link}
                        href={`/a-service-dashboard`}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        {"Service\nDashboard"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__kVooB
                        )}
                        component={Link}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        {"Market\nTrends"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__ztJCd
                        )}
                        component={Link}
                        href={""}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        {"Find a \nbusiness"}
                      </PlasmicLink__>
                    </React.Fragment>
                  }
                  openButton={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__jF5Ho)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      height={``}
                      src={"https://static1.plasmic.app/menu.svg"}
                      width={``}
                    />
                  }
                  responsiveBreakpoint={768}
                />

                <AntdDropdown
                  data-plasmic-name={"account2"}
                  data-plasmic-override={overrides.account2}
                  className={classNames("__wab_instance", sty.account2)}
                  dropdownMenuScopeClassName={sty["account2__dropdownMenu"]}
                  menuItems={() => (
                    <React.Fragment>
                      <AntdMenuItem
                        className={classNames(
                          "__wab_instance",
                          sty.menuItem__s1BYq
                        )}
                        key={"menu-item-1"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__smOcv
                          )}
                        >
                          {"Menu item"}
                        </div>
                      </AntdMenuItem>
                      <AntdMenuItem
                        className={classNames(
                          "__wab_instance",
                          sty.menuItem__hZfEv
                        )}
                        key={"menu-item-2"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rnwkP
                          )}
                        >
                          {"Menu item"}
                        </div>
                      </AntdMenuItem>
                    </React.Fragment>
                  )}
                  menuItemsJson={(() => {
                    const __composite = [
                      { type: null, label: null, children: null },
                      {
                        type: null,
                        value: "action1",
                        label: null,
                        children: null
                      },
                      {
                        type: null,
                        value: "action2",
                        label: null,
                        onClick: null
                      }
                    ];
                    __composite["0"]["type"] = "group";
                    __composite["0"]["label"] = "User";
                    __composite["0"]["children"] = (() => {
                      const __composite = [
                        { type: "item", label: null, onClick: null },
                        { type: "item", label: null, onClick: null },
                        { type: null }
                      ];
                      __composite["0"]["label"] = "Profile";
                      __composite["1"]["label"] = "Edit profile";
                      __composite["2"]["type"] = "divider";
                      return __composite;
                    })();
                    __composite["1"]["type"] = "group";
                    __composite["1"]["label"] = "Account";
                    __composite["1"]["children"] = (() => {
                      const __composite = [
                        { type: "item", label: null, onClick: null },
                        { type: "item", label: null, onClick: null },
                        { type: null }
                      ];
                      __composite["0"]["label"] = "Settings & Privacy";
                      __composite["1"]["label"] = "Help";
                      __composite["2"]["type"] = "divider";
                      return __composite;
                    })();
                    __composite["2"]["type"] = "item";
                    __composite["2"]["label"] = "Sign out";
                    return __composite;
                  })()}
                  trigger={"hover"}
                  useMenuItemsSlot={false}
                >
                  <AntdButton
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames("__wab_instance", sty.button)}
                    target={true}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__iLpIl)}
                      displayHeight={"30px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"30px"}
                      loading={"lazy"}
                      src={(() => {
                        try {
                          return $props.formData?.["Profile pic"] ?? null;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}
                    />
                  </AntdButton>
                </AntdDropdown>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"container1"}
            data-plasmic-override={overrides.container1}
            className={classNames(projectcss.all, sty.container1)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__x4Xl)}>
              <div className={classNames(projectcss.all, sty.freeBox__stduf)}>
                <PlasmicImg__
                  data-plasmic-name={"profilePic"}
                  data-plasmic-override={overrides.profilePic}
                  alt={""}
                  className={classNames(sty.profilePic)}
                  displayHeight={"100px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100px"}
                  loading={"lazy"}
                />

                <PlasmicImg__
                  data-plasmic-name={"communityLogo"}
                  data-plasmic-override={overrides.communityLogo}
                  alt={""}
                  className={classNames(sty.communityLogo)}
                  displayHeight={"50px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"50px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/ez_marketing_platform_sacanagem/images/semTitulo2Jpg3.jpg",
                    fullWidth: 1014,
                    fullHeight: 1014,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__rxQph)}>
                <div className={classNames(projectcss.all, sty.freeBox__na8Ob)}>
                  <div
                    data-plasmic-name={"firstName"}
                    data-plasmic-override={overrides.firstName}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.firstName
                    )}
                  >
                    {"Name"}
                  </div>
                  <div
                    data-plasmic-name={"lastName"}
                    data-plasmic-override={overrides.lastName}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.lastName
                    )}
                  >
                    {"Last Name"}
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___96Bja)}
                >
                  <div
                    data-plasmic-name={"age"}
                    data-plasmic-override={overrides.age}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.age
                    )}
                  >
                    {"28"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__odfi9
                    )}
                  >
                    {"years"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"location"}
                  data-plasmic-override={overrides.location}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.location
                  )}
                >
                  {"New York"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___3GrDu)}>
                <div className={classNames(projectcss.all, sty.freeBox__ygidJ)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__arrNd
                    )}
                  >
                    {"Speciality"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__ftc6Q)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nqpsw
                    )}
                  >
                    {"Speciality"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__slkFd)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kpPmb
                    )}
                  >
                    {"Speciality"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__wMnmk)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__het3J
                    )}
                  >
                    {"Speciality"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__vg2H)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__b0Npj
                    )}
                  >
                    {"Speciality"}
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__g8Zmt)}>
                <div className={classNames(projectcss.all, sty.freeBox__aW6Ek)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cOWc
                    )}
                  >
                    {"Bacharel"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bmEpX
                    )}
                  >
                    {"Gold"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"charge"}
                  data-plasmic-override={overrides.charge}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.charge
                  )}
                >
                  {"Charge"}
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__guiX)}>
              <div className={classNames(projectcss.all, sty.freeBox___7NugK)}>
                <Icon4Icon
                  className={classNames(projectcss.all, sty.svg__ba0K)}
                  role={"img"}
                />

                <PlasmicLink__
                  data-plasmic-name={"linkedIn"}
                  data-plasmic-override={overrides.linkedIn}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.linkedIn
                  )}
                  component={Link}
                  href={"https://www.plasmic.app/"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {"LinkedIn"}
                </PlasmicLink__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__bhwH)}>
                <Icon6Icon
                  className={classNames(projectcss.all, sty.svg__frtId)}
                  role={"img"}
                />

                <PlasmicLink__
                  data-plasmic-name={"instagram"}
                  data-plasmic-override={overrides.instagram}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.instagram
                  )}
                  component={Link}
                  href={"https://www.plasmic.app/"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {"Instagram"}
                </PlasmicLink__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__yjigd)}>
                <IlustrgatuSvgIcon
                  className={classNames(projectcss.all, sty.svg__qyBkv)}
                  role={"img"}
                />

                <PlasmicLink__
                  data-plasmic-name={"x"}
                  data-plasmic-override={overrides.x}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.x
                  )}
                  component={Link}
                  href={"https://www.plasmic.app/"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {"X corporation"}
                </PlasmicLink__>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"rateThisMember"}
            data-plasmic-override={overrides.rateThisMember}
            className={classNames(projectcss.all, sty.rateThisMember)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__orRwc
              )}
            >
              {"Rate this member"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__sqQcT
              )}
            >
              {"07/2025 - 10/2025"}
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__xg27G)}>
              <div className={classNames(projectcss.all, sty.freeBox__vIyaE)}>
                <PoliteSvgIcon
                  className={classNames(projectcss.all, sty.svg__scGb9)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fqscL
                  )}
                >
                  {"Ethics (Behavior)"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2UvpS
                  )}
                >
                  {
                    "Meeting deadlines and commitments\r\n\r\nCollaborative attitude\r\n\r\nRespectful and professional communication\r\n\r\nTransparency in deliveries\r"
                  }
                </div>
                <Modal
                  data-plasmic-name={"rate"}
                  data-plasmic-override={overrides.rate}
                  className={classNames("__wab_instance", sty.rate)}
                  content={
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___1Ar1T
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ljylu
                        )}
                      >
                        {
                          "Leave a comment, try to share your experience and your expectations or disappointments."
                        }
                      </div>
                      {(() => {
                        const child$Props = {
                          className: classNames("__wab_instance", sty.comment),
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["comment", "value"],
                              AntdTextArea_Helpers
                            ).apply(null, eventArgs);
                          },
                          value: generateStateValueProp($state, [
                            "comment",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "comment.value"
                            }
                          ],
                          [],
                          AntdTextArea_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <AntdTextArea
                            data-plasmic-name={"comment"}
                            data-plasmic-override={overrides.comment}
                            {...child$Props}
                          />
                        );
                      })()}
                    </div>
                  }
                  footer={
                    <div
                      className={classNames(projectcss.all, sty.freeBox__x04ND)}
                    >
                      <Button2
                        data-plasmic-name={"confirmRate"}
                        data-plasmic-override={overrides.confirmRate}
                        color={"muted"}
                        label={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__lVxXy
                            )}
                          >
                            {"Confirm"}
                          </div>
                        }
                        onClick={async event => {
                          const $steps = {};

                          $steps["updateModalIsOpen"] = true
                            ? (() => {
                                const actionArgs = {
                                  variable: {
                                    objRoot: $state,
                                    variablePath: ["rate", "isOpen"]
                                  },
                                  operation: 0,
                                  value: false
                                };
                                return (({
                                  variable,
                                  value,
                                  startIndex,
                                  deleteCount
                                }) => {
                                  if (!variable) {
                                    return;
                                  }
                                  const { objRoot, variablePath } = variable;

                                  $stateSet(objRoot, variablePath, value);
                                  return value;
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["updateModalIsOpen"] != null &&
                            typeof $steps["updateModalIsOpen"] === "object" &&
                            typeof $steps["updateModalIsOpen"].then ===
                              "function"
                          ) {
                            $steps["updateModalIsOpen"] =
                              await $steps["updateModalIsOpen"];
                          }
                        }}
                        size={"extraSmall"}
                        type={"soft"}
                      />

                      <Button2
                        color={"muted"}
                        label={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__iwA6
                            )}
                          >
                            {"Cancel"}
                          </div>
                        }
                        onClick={async event => {
                          const $steps = {};

                          $steps["updateModalIsOpen"] = true
                            ? (() => {
                                const actionArgs = {
                                  variable: {
                                    objRoot: $state,
                                    variablePath: ["rate", "isOpen"]
                                  },
                                  operation: 0,
                                  value: false
                                };
                                return (({
                                  variable,
                                  value,
                                  startIndex,
                                  deleteCount
                                }) => {
                                  if (!variable) {
                                    return;
                                  }
                                  const { objRoot, variablePath } = variable;

                                  $stateSet(objRoot, variablePath, value);
                                  return value;
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["updateModalIsOpen"] != null &&
                            typeof $steps["updateModalIsOpen"] === "object" &&
                            typeof $steps["updateModalIsOpen"].then ===
                              "function"
                          ) {
                            $steps["updateModalIsOpen"] =
                              await $steps["updateModalIsOpen"];
                          }
                        }}
                        size={"extraSmall"}
                        type={"soft"}
                      />
                    </div>
                  }
                  heading={
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__zStnQ
                      )}
                    >
                      {"Rating"}
                    </h3>
                  }
                  isOpen={generateStateValueProp($state, ["rate", "isOpen"])}
                  onOpenChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, ["rate", "isOpen"]).apply(
                      null,
                      eventArgs
                    );

                    if (
                      eventArgs.length > 1 &&
                      eventArgs[1] &&
                      eventArgs[1]._plasmic_state_init_
                    ) {
                      return;
                    }
                  }}
                  trigger={
                    <AntdRate
                      data-plasmic-name={"rating"}
                      data-plasmic-override={overrides.rating}
                      allowHalf={true}
                      className={classNames("__wab_instance", sty.rating)}
                      onChange={async (...eventArgs: any) => {
                        generateStateOnChangeProp($state, [
                          "rating",
                          "value"
                        ]).apply(null, eventArgs);
                      }}
                      symbols={
                        <React.Fragment>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___4UPFs
                            )}
                          >
                            {"1"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__zuY1
                            )}
                          >
                            {"2"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__znRp
                            )}
                          >
                            {"3"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___5NCgn
                            )}
                          >
                            {"4"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__fJdwB
                            )}
                          >
                            {"5"}
                          </div>
                        </React.Fragment>
                      }
                      value={generateStateValueProp($state, [
                        "rating",
                        "value"
                      ])}
                    />
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__tManG)}>
                <SkillSvgIcon
                  className={classNames(projectcss.all, sty.svg__heMmM)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nkT3
                  )}
                >
                  {"Technical Performance"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__smu0A
                  )}
                >
                  {
                    "Quality of deliveries\r\n\r\nTechnical mastery of tools\r\n\r\nAdaptation to project demands"
                  }
                </div>
                <Modal
                  data-plasmic-name={"rate2"}
                  data-plasmic-override={overrides.rate2}
                  className={classNames("__wab_instance", sty.rate2)}
                  content={
                    <div
                      className={classNames(projectcss.all, sty.freeBox__apzRs)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___2Xivz
                        )}
                      >
                        {
                          "Leave a comment, try to share your experience and your expectations or disappointments."
                        }
                      </div>
                      {(() => {
                        const child$Props = {
                          className: classNames("__wab_instance", sty.comment2),
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["comment2", "value"],
                              AntdTextArea_Helpers
                            ).apply(null, eventArgs);
                          },
                          value: generateStateValueProp($state, [
                            "comment2",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "comment2.value"
                            }
                          ],
                          [],
                          AntdTextArea_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <AntdTextArea
                            data-plasmic-name={"comment2"}
                            data-plasmic-override={overrides.comment2}
                            {...child$Props}
                          />
                        );
                      })()}
                    </div>
                  }
                  footer={
                    <div
                      className={classNames(projectcss.all, sty.freeBox__kmvbU)}
                    >
                      <Button2
                        data-plasmic-name={"confirmRate2"}
                        data-plasmic-override={overrides.confirmRate2}
                        color={"muted"}
                        label={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__fVsX
                            )}
                          >
                            {"Confirm"}
                          </div>
                        }
                        onClick={async event => {
                          const $steps = {};

                          $steps["updateModalIsOpen"] = true
                            ? (() => {
                                const actionArgs = {
                                  variable: {
                                    objRoot: $state,
                                    variablePath: ["rate2", "isOpen"]
                                  },
                                  operation: 0,
                                  value: false
                                };
                                return (({
                                  variable,
                                  value,
                                  startIndex,
                                  deleteCount
                                }) => {
                                  if (!variable) {
                                    return;
                                  }
                                  const { objRoot, variablePath } = variable;

                                  $stateSet(objRoot, variablePath, value);
                                  return value;
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["updateModalIsOpen"] != null &&
                            typeof $steps["updateModalIsOpen"] === "object" &&
                            typeof $steps["updateModalIsOpen"].then ===
                              "function"
                          ) {
                            $steps["updateModalIsOpen"] =
                              await $steps["updateModalIsOpen"];
                          }
                        }}
                        size={"extraSmall"}
                        type={"soft"}
                      />

                      <Button2
                        color={"muted"}
                        label={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__rtmYk
                            )}
                          >
                            {"Cancel"}
                          </div>
                        }
                        onClick={async event => {
                          const $steps = {};

                          $steps["updateModalIsOpen"] = true
                            ? (() => {
                                const actionArgs = {
                                  variable: {
                                    objRoot: $state,
                                    variablePath: ["rate2", "isOpen"]
                                  },
                                  operation: 0,
                                  value: false
                                };
                                return (({
                                  variable,
                                  value,
                                  startIndex,
                                  deleteCount
                                }) => {
                                  if (!variable) {
                                    return;
                                  }
                                  const { objRoot, variablePath } = variable;

                                  $stateSet(objRoot, variablePath, value);
                                  return value;
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["updateModalIsOpen"] != null &&
                            typeof $steps["updateModalIsOpen"] === "object" &&
                            typeof $steps["updateModalIsOpen"].then ===
                              "function"
                          ) {
                            $steps["updateModalIsOpen"] =
                              await $steps["updateModalIsOpen"];
                          }
                        }}
                        size={"extraSmall"}
                        type={"soft"}
                      />
                    </div>
                  }
                  heading={
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3___2Qe19
                      )}
                    >
                      {"Rating"}
                    </h3>
                  }
                  isOpen={generateStateValueProp($state, ["rate2", "isOpen"])}
                  onOpenChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "rate2",
                      "isOpen"
                    ]).apply(null, eventArgs);

                    if (
                      eventArgs.length > 1 &&
                      eventArgs[1] &&
                      eventArgs[1]._plasmic_state_init_
                    ) {
                      return;
                    }
                  }}
                  trigger={
                    <AntdRate
                      data-plasmic-name={"rateTechnical"}
                      data-plasmic-override={overrides.rateTechnical}
                      allowHalf={true}
                      className={classNames(
                        "__wab_instance",
                        sty.rateTechnical
                      )}
                      onChange={async (...eventArgs: any) => {
                        generateStateOnChangeProp($state, [
                          "rateTechnical",
                          "value"
                        ]).apply(null, eventArgs);
                      }}
                      symbols={
                        <React.Fragment>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___55Bkp
                            )}
                          >
                            {"1"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gbIad
                            )}
                          >
                            {"2"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__dcz33
                            )}
                          >
                            {"3"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___55GVv
                            )}
                          >
                            {"4"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__mJhhy
                            )}
                          >
                            {"5"}
                          </div>
                        </React.Fragment>
                      }
                      value={generateStateValueProp($state, [
                        "rateTechnical",
                        "value"
                      ])}
                    />
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__kY7Wq)}>
                <CustomerRatesSvgIcon
                  className={classNames(projectcss.all, sty.svg__tHvpk)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tKeZ
                  )}
                >
                  {"This member has rated your agency"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__q7P4
                  )}
                >
                  {
                    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                  }
                </div>
                <AntdRate
                  data-plasmic-name={"memberRated"}
                  data-plasmic-override={overrides.memberRated}
                  allowHalf={true}
                  className={classNames("__wab_instance", sty.memberRated)}
                  disabled={true}
                  onChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "memberRated",
                      "value"
                    ]).apply(null, eventArgs);
                  }}
                  symbols={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oaFrS
                        )}
                      >
                        {"1"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3Z82Y
                        )}
                      >
                        {"2"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___37S2W
                        )}
                      >
                        {"3"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pmhqm
                        )}
                      >
                        {"4"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__f3Zm
                        )}
                      >
                        {"5"}
                      </div>
                    </React.Fragment>
                  }
                  value={generateStateValueProp($state, [
                    "memberRated",
                    "value"
                  ])}
                />
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__faEn8)}>
            <div className={classNames(projectcss.all, sty.freeBox__vUacO)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__sfqy
                )}
              >
                {"Enter some text"}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__qeqRh)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__aOsl
                  )}
                >
                  {"Ethics"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__niuFb
                  )}
                >
                  {"Technical Performance"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3Msrp
                  )}
                >
                  {"Member rated"}
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"reportRate"}
              data-plasmic-override={overrides.reportRate}
              className={classNames(projectcss.all, sty.reportRate)}
            >
              <div
                data-plasmic-name={"reportDate"}
                data-plasmic-override={overrides.reportDate}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.reportDate
                )}
              >
                {"07/2025 - 10/2025"}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__ihZl0)}>
                <AntdRate
                  data-plasmic-name={"ethics"}
                  data-plasmic-override={overrides.ethics}
                  allowHalf={true}
                  className={classNames("__wab_instance", sty.ethics)}
                  disabled={true}
                  onChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "ethics",
                      "value"
                    ]).apply(null, eventArgs);
                  }}
                  symbols={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hIOt7
                        )}
                      >
                        {"1"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___0I1Bx
                        )}
                      >
                        {"2"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__q1MrV
                        )}
                      >
                        {"3"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ecRzq
                        )}
                      >
                        {"4"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___974Yq
                        )}
                      >
                        {"5"}
                      </div>
                    </React.Fragment>
                  }
                  value={generateStateValueProp($state, ["ethics", "value"])}
                />

                <AntdRate
                  data-plasmic-name={"technicalPerformance"}
                  data-plasmic-override={overrides.technicalPerformance}
                  allowHalf={true}
                  className={classNames(
                    "__wab_instance",
                    sty.technicalPerformance
                  )}
                  disabled={true}
                  onChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "technicalPerformance",
                      "value"
                    ]).apply(null, eventArgs);
                  }}
                  symbols={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___9WAh4
                        )}
                      >
                        {"1"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___6Jre7
                        )}
                      >
                        {"2"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uVjmo
                        )}
                      >
                        {"3"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jCuXt
                        )}
                      >
                        {"4"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ibKkn
                        )}
                      >
                        {"5"}
                      </div>
                    </React.Fragment>
                  }
                  value={generateStateValueProp($state, [
                    "technicalPerformance",
                    "value"
                  ])}
                />

                <AntdRate
                  data-plasmic-name={"memberRated2"}
                  data-plasmic-override={overrides.memberRated2}
                  allowHalf={true}
                  className={classNames("__wab_instance", sty.memberRated2)}
                  disabled={true}
                  onChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "memberRated2",
                      "value"
                    ]).apply(null, eventArgs);
                  }}
                  symbols={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yF0Yx
                        )}
                      >
                        {"1"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ayawh
                        )}
                      >
                        {"2"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__sEy2T
                        )}
                      >
                        {"3"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___8LIss
                        )}
                      >
                        {"4"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qu2OE
                        )}
                      >
                        {"5"}
                      </div>
                    </React.Fragment>
                  }
                  value={generateStateValueProp($state, [
                    "memberRated2",
                    "value"
                  ])}
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "topBarAuto",
    "navigationBar",
    "account2",
    "button",
    "container1",
    "profilePic",
    "communityLogo",
    "firstName",
    "lastName",
    "age",
    "location",
    "charge",
    "linkedIn",
    "instagram",
    "x",
    "rateThisMember",
    "rate",
    "rating",
    "comment",
    "confirmRate",
    "rate2",
    "rateTechnical",
    "comment2",
    "confirmRate2",
    "memberRated",
    "reportRate",
    "reportDate",
    "ethics",
    "technicalPerformance",
    "memberRated2"
  ],
  topBarAuto: ["topBarAuto", "navigationBar", "account2", "button"],
  navigationBar: ["navigationBar"],
  account2: ["account2", "button"],
  button: ["button"],
  container1: [
    "container1",
    "profilePic",
    "communityLogo",
    "firstName",
    "lastName",
    "age",
    "location",
    "charge",
    "linkedIn",
    "instagram",
    "x"
  ],
  profilePic: ["profilePic"],
  communityLogo: ["communityLogo"],
  firstName: ["firstName"],
  lastName: ["lastName"],
  age: ["age"],
  location: ["location"],
  charge: ["charge"],
  linkedIn: ["linkedIn"],
  instagram: ["instagram"],
  x: ["x"],
  rateThisMember: [
    "rateThisMember",
    "rate",
    "rating",
    "comment",
    "confirmRate",
    "rate2",
    "rateTechnical",
    "comment2",
    "confirmRate2",
    "memberRated"
  ],
  rate: ["rate", "rating", "comment", "confirmRate"],
  rating: ["rating"],
  comment: ["comment"],
  confirmRate: ["confirmRate"],
  rate2: ["rate2", "rateTechnical", "comment2", "confirmRate2"],
  rateTechnical: ["rateTechnical"],
  comment2: ["comment2"],
  confirmRate2: ["confirmRate2"],
  memberRated: ["memberRated"],
  reportRate: [
    "reportRate",
    "reportDate",
    "ethics",
    "technicalPerformance",
    "memberRated2"
  ],
  reportDate: ["reportDate"],
  ethics: ["ethics"],
  technicalPerformance: ["technicalPerformance"],
  memberRated2: ["memberRated2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  topBarAuto: "div";
  navigationBar: typeof NavigationBar;
  account2: typeof AntdDropdown;
  button: typeof AntdButton;
  container1: "div";
  profilePic: typeof PlasmicImg__;
  communityLogo: typeof PlasmicImg__;
  firstName: "div";
  lastName: "div";
  age: "div";
  location: "div";
  charge: "div";
  linkedIn: "a";
  instagram: "a";
  x: "a";
  rateThisMember: "div";
  rate: typeof Modal;
  rating: typeof AntdRate;
  comment: typeof AntdTextArea;
  confirmRate: typeof Button2;
  rate2: typeof Modal;
  rateTechnical: typeof AntdRate;
  comment2: typeof AntdTextArea;
  confirmRate2: typeof Button2;
  memberRated: typeof AntdRate;
  reportRate: "div";
  reportDate: "div";
  ethics: typeof AntdRate;
  technicalPerformance: typeof AntdRate;
  memberRated2: typeof AntdRate;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicARatingMembers__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicARatingMembers__VariantsArgs;
    args?: PlasmicARatingMembers__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicARatingMembers__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicARatingMembers__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicARatingMembers__ArgProps,
          internalVariantPropNames: PlasmicARatingMembers__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicARatingMembers__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicARatingMembers";
  } else {
    func.displayName = `PlasmicARatingMembers.${nodeName}`;
  }
  return func;
}

export const PlasmicARatingMembers = Object.assign(
  // Top-level PlasmicARatingMembers renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    topBarAuto: makeNodeComponent("topBarAuto"),
    navigationBar: makeNodeComponent("navigationBar"),
    account2: makeNodeComponent("account2"),
    button: makeNodeComponent("button"),
    container1: makeNodeComponent("container1"),
    profilePic: makeNodeComponent("profilePic"),
    communityLogo: makeNodeComponent("communityLogo"),
    firstName: makeNodeComponent("firstName"),
    lastName: makeNodeComponent("lastName"),
    age: makeNodeComponent("age"),
    location: makeNodeComponent("location"),
    charge: makeNodeComponent("charge"),
    linkedIn: makeNodeComponent("linkedIn"),
    instagram: makeNodeComponent("instagram"),
    x: makeNodeComponent("x"),
    rateThisMember: makeNodeComponent("rateThisMember"),
    rate: makeNodeComponent("rate"),
    rating: makeNodeComponent("rating"),
    comment: makeNodeComponent("comment"),
    confirmRate: makeNodeComponent("confirmRate"),
    rate2: makeNodeComponent("rate2"),
    rateTechnical: makeNodeComponent("rateTechnical"),
    comment2: makeNodeComponent("comment2"),
    confirmRate2: makeNodeComponent("confirmRate2"),
    memberRated: makeNodeComponent("memberRated"),
    reportRate: makeNodeComponent("reportRate"),
    reportDate: makeNodeComponent("reportDate"),
    ethics: makeNodeComponent("ethics"),
    technicalPerformance: makeNodeComponent("technicalPerformance"),
    memberRated2: makeNodeComponent("memberRated2"),

    // Metadata about props expected for PlasmicARatingMembers
    internalVariantProps: PlasmicARatingMembers__VariantProps,
    internalArgProps: PlasmicARatingMembers__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/a-rating-members",
      pagePath: "/a-rating-members",
      params: {},
      query: {}
    })
  }
);

export default PlasmicARatingMembers;
/* prettier-ignore-end */
