/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5uU4LbmmcY9V8oBke7M62e
// Component: mNhEKeaIVa9V

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import { AntdDropdown } from "@plasmicpkgs/antd5/skinny/registerDropdown";
import { AntdMenuItem } from "@plasmicpkgs/antd5/skinny/registerMenu";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { SliderWrapper } from "@plasmicpkgs/react-slick";
import { sliderHelpers as SliderWrapper_Helpers } from "@plasmicpkgs/react-slick";
import Modal from "../../Modal"; // plasmic-import: 2mIwXeE-_Psc/component
import { AntdRate } from "@plasmicpkgs/antd5/skinny/registerRate";
import { AntdTextArea } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdTextArea_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import Button2 from "../../Button2"; // plasmic-import: t1SFzVEz5RlV/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 5uU4LbmmcY9V8oBke7M62e/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 5uU4LbmmcY9V8oBke7M62e/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 5uU4LbmmcY9V8oBke7M62e/projectcss
import sty from "./PlasmicCRateACommunitie.module.css"; // plasmic-import: mNhEKeaIVa9V/css

import SemTitulo2SvgIcon from "./icons/PlasmicIcon__SemTitulo2Svg"; // plasmic-import: Nb_GErn1yi4Z/icon
import CustomerKnowledgeSvgIcon from "./icons/PlasmicIcon__CustomerKnowledgeSvg"; // plasmic-import: YMJJ4lfeZ6ds/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: l4RREmL1A-vM/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: qJDdQLGS2RlC/icon
import YourAverageRateSvgIcon from "./icons/PlasmicIcon__YourAverageRateSvg"; // plasmic-import: 182P-Ny0NQeA/icon
import CustomerRatesSvgIcon from "./icons/PlasmicIcon__CustomerRatesSvg"; // plasmic-import: ayP013CUNl9_/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "Rate a community",

    openGraph: {
      title: "Rate a community"
    },
    twitter: {
      card: "summary" as const,
      title: "Rate a community"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicCRateACommunitie__VariantMembers = {};
export type PlasmicCRateACommunitie__VariantsArgs = {};
type VariantPropType = keyof PlasmicCRateACommunitie__VariantsArgs;
export const PlasmicCRateACommunitie__VariantProps =
  new Array<VariantPropType>();

export type PlasmicCRateACommunitie__ArgsType = {};
type ArgPropType = keyof PlasmicCRateACommunitie__ArgsType;
export const PlasmicCRateACommunitie__ArgProps = new Array<ArgPropType>();

export type PlasmicCRateACommunitie__OverridesType = {
  root?: Flex__<"div">;
  topBarAuto?: Flex__<"div">;
  navigationBar?: Flex__<typeof NavigationBar>;
  account2?: Flex__<typeof AntdDropdown>;
  button?: Flex__<typeof AntdButton>;
  container3?: Flex__<"div">;
  communityLogo2?: Flex__<typeof PlasmicImg__>;
  type2?: Flex__<"svg">;
  communityName2?: Flex__<"div">;
  membersCarousel?: Flex__<typeof SliderWrapper>;
  member2?: Flex__<"div">;
  office2?: Flex__<"div">;
  profilePic2?: Flex__<typeof PlasmicImg__>;
  rateThisAgency?: Flex__<"div">;
  actualData?: Flex__<"div">;
  rate?: Flex__<typeof Modal>;
  rating?: Flex__<typeof AntdRate>;
  h3?: Flex__<"h3">;
  comment?: Flex__<typeof AntdTextArea>;
  confirmRate?: Flex__<typeof Button2>;
  button2?: Flex__<typeof Button2>;
  agencysRate?: Flex__<typeof AntdRate>;
  customerRated?: Flex__<typeof AntdRate>;
  reportRate?: Flex__<"div">;
  reportData?: Flex__<"div">;
  customerInstruction?: Flex__<typeof AntdRate>;
  agencyRate?: Flex__<typeof AntdRate>;
  averageRatingReceived?: Flex__<typeof AntdRate>;
};

export interface DefaultCRateACommunitieProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCRateACommunitie__RenderFunc(props: {
  variants: PlasmicCRateACommunitie__VariantsArgs;
  args: PlasmicCRateACommunitie__ArgsType;
  overrides: PlasmicCRateACommunitie__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const $globalActions = useGlobalActions?.();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "rate.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "rating.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          $props.formData?.company_rate ?? 0
      },
      {
        path: "comment.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdTextArea_Helpers)
      },
      {
        path: "agencysRate.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          $props.formData?.agency_rate ?? 0
      },
      {
        path: "customerRated.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          $props.formData?.customer_rate ?? 0
      },
      {
        path: "agencyRate[].value",
        type: "private",
        variableType: "number"
      },
      {
        path: "customerInstruction[].value",
        type: "private",
        variableType: "number"
      },
      {
        path: "averageRatingReceived[].value",
        type: "private",
        variableType: "number"
      },
      {
        path: "membersCarousel.currentSlide",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => 0,

        refName: "membersCarousel",
        onMutate: generateOnMutateForSpec("currentSlide", SliderWrapper_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          styleTokensClassNames,
          sty.root
        )}
      >
        <div
          data-plasmic-name={"topBarAuto"}
          data-plasmic-override={overrides.topBarAuto}
          className={classNames(projectcss.all, sty.topBarAuto)}
        >
          <div className={classNames(projectcss.all, sty.freeBox___2WZiJ)}>
            <div className={classNames(projectcss.all, sty.freeBox___81UPp)}>
              <NavigationBar
                data-plasmic-name={"navigationBar"}
                data-plasmic-override={overrides.navigationBar}
                brand={
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.a__5uU4L,
                      sty.link___5D8Or
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__ekXnw)}
                      displayHeight={"30px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      src={{
                        src: "/plasmic/ez_marketing_platform_sacanagem/images/ezSvg2.svg",
                        fullWidth: 60,
                        fullHeight: 31,
                        aspectRatio: undefined
                      }}
                    />
                  </PlasmicLink__>
                }
                className={classNames("__wab_instance", sty.navigationBar)}
                closeButton={
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___6YT2R)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={"https://static1.plasmic.app/close.svg"}
                  />
                }
                itemsGap={8}
                menuItems={
                  <React.Fragment>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.a__5uU4L,
                        projectcss.__wab_text,
                        sty.link__kNpqn
                      )}
                      component={Link}
                      href={`/c-company-profile`}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      {"Company \nProfile"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.a__5uU4L,
                        projectcss.__wab_text,
                        sty.link__aj40X
                      )}
                      component={Link}
                      href={`/c-services-dashboard`}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      {"Service\nDashboard"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.a__5uU4L,
                        projectcss.__wab_text,
                        sty.link__m1UYf
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      {"Market\nTrends"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.a__5uU4L,
                        projectcss.__wab_text,
                        sty.link__rAhia
                      )}
                      component={Link}
                      href={`/c-find-a-affiliate`}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      {"Find a \naffiliate"}
                    </PlasmicLink__>
                  </React.Fragment>
                }
                openButton={
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__gw1IK)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    height={``}
                    src={"https://static1.plasmic.app/menu.svg"}
                    width={``}
                  />
                }
                responsiveBreakpoint={768}
              />

              <AntdDropdown
                data-plasmic-name={"account2"}
                data-plasmic-override={overrides.account2}
                className={classNames("__wab_instance", sty.account2)}
                dropdownMenuScopeClassName={sty["account2__dropdownMenu"]}
                menuClassName={classNames({ [sty["pcls_zfK0dg96L-Hk"]]: true })}
                menuItemClassName={classNames({
                  [sty["pcls_w_OWUPt1-JB-"]]: true
                })}
                menuItems={() => (
                  <React.Fragment>
                    <AntdMenuItem
                      className={classNames(
                        "__wab_instance",
                        sty.menuItem__q4LlZ
                      )}
                      key={"menu-item-1"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wuQnd
                        )}
                      >
                        {"Menu item"}
                      </div>
                    </AntdMenuItem>
                    <AntdMenuItem
                      className={classNames(
                        "__wab_instance",
                        sty.menuItem__mksvu
                      )}
                      key={"menu-item-2"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wEnIb
                        )}
                      >
                        {"Menu item"}
                      </div>
                    </AntdMenuItem>
                  </React.Fragment>
                )}
                menuItemsJson={(() => {
                  const __composite = [
                    {
                      type: null,
                      value: "action1",
                      label: null,
                      children: null
                    },
                    {
                      type: null,
                      value: "action2",
                      label: null,
                      onClick: null
                    },
                    { type: "item" }
                  ];
                  __composite["0"]["type"] = "group";
                  __composite["0"]["label"] = "Account";
                  __composite["0"]["children"] = (() => {
                    const __composite = [
                      { type: "item", label: null, onClick: null },
                      { type: "item", label: null, onClick: null },
                      { type: null }
                    ];
                    __composite["0"]["label"] = "Settings & Privacy";
                    __composite["0"]["onClick"] = async info => {
                      const $steps = {};

                      $steps["goToALogin"] = true
                        ? (() => {
                            const actionArgs = { destination: `/a-login` };
                            return (({ destination }) => {
                              if (
                                typeof destination === "string" &&
                                destination.startsWith("#")
                              ) {
                                document
                                  .getElementById(destination.substr(1))
                                  .scrollIntoView({ behavior: "smooth" });
                              } else {
                                __nextRouter?.push(destination);
                              }
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["goToALogin"] != null &&
                        typeof $steps["goToALogin"] === "object" &&
                        typeof $steps["goToALogin"].then === "function"
                      ) {
                        $steps["goToALogin"] = await $steps["goToALogin"];
                      }
                    };
                    __composite["1"]["label"] = "Help";
                    __composite["1"]["onClick"] = async info => {
                      const $steps = {};

                      $steps["invokeGlobalAction"] = true
                        ? (() => {
                            const actionArgs = {
                              args: [
                                undefined,
                                "aaaaaaaaaaaaaaaa",
                                "sssssssssssssssss"
                              ]
                            };
                            return $globalActions[
                              "plasmic-antd5-config-provider.showNotification"
                            ]?.apply(null, [...actionArgs.args]);
                          })()
                        : undefined;
                      if (
                        $steps["invokeGlobalAction"] != null &&
                        typeof $steps["invokeGlobalAction"] === "object" &&
                        typeof $steps["invokeGlobalAction"].then === "function"
                      ) {
                        $steps["invokeGlobalAction"] =
                          await $steps["invokeGlobalAction"];
                      }
                    };
                    __composite["2"]["type"] = "divider";
                    return __composite;
                  })();
                  __composite["1"]["type"] = "item";
                  __composite["1"]["label"] = "Sign out";
                  __composite["1"]["onClick"] = async info => {
                    const $steps = {};

                    $steps["runCode"] = true
                      ? (() => {
                          const actionArgs = {
                            customFunction: async () => {
                              return $props.onLogout?.();
                            }
                          };
                          return (({ customFunction }) => {
                            return customFunction();
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["runCode"] != null &&
                      typeof $steps["runCode"] === "object" &&
                      typeof $steps["runCode"].then === "function"
                    ) {
                      $steps["runCode"] = await $steps["runCode"];
                    }
                  };
                  return __composite;
                })()}
                trigger={"hover"}
                useMenuItemsSlot={false}
              >
                <AntdButton
                  data-plasmic-name={"button"}
                  data-plasmic-override={overrides.button}
                  className={classNames("__wab_instance", sty.button)}
                  target={true}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__a0Oxu)}
                    displayHeight={"30px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"30px"}
                    loading={"lazy"}
                  />
                </AntdButton>
              </AntdDropdown>
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"container3"}
          data-plasmic-override={overrides.container3}
          className={classNames(projectcss.all, sty.container3)}
        >
          <div className={classNames(projectcss.all, sty.freeBox__n1Ndr)}>
            <PlasmicImg__
              data-plasmic-name={"communityLogo2"}
              data-plasmic-override={overrides.communityLogo2}
              alt={""}
              className={classNames(sty.communityLogo2)}
              displayHeight={"100px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"100px"}
              loading={"lazy"}
              src={(() => {
                try {
                  return $props.formData?.["community_logo"] ?? null;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return {
                      src: "/plasmic/ez_marketing_platform_sacanagem/images/semTitulo2Jpg3.jpg",
                      fullWidth: 1014,
                      fullHeight: 1014,
                      aspectRatio: undefined
                    };
                  }
                  throw e;
                }
              })()}
            />

            <SemTitulo2SvgIcon
              data-plasmic-name={"type2"}
              data-plasmic-override={overrides.type2}
              className={classNames(projectcss.all, sty.type2)}
              role={"img"}
            />

            <div
              data-plasmic-name={"communityName2"}
              data-plasmic-override={overrides.communityName2}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.communityName2
              )}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return (
                      $props.formData?.["community_name"] ?? "Community name"
                    );
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "Community";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__eKPlz)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ufHmP
              )}
            >
              {"Gold"}
            </div>
            {(() => {
              const child$Props = {
                arrows: false,
                beforeChange: async (...eventArgs: any) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "currentSlide",
                    ["membersCarousel", "currentSlide"],
                    SliderWrapper_Helpers
                  ).apply(null, eventArgs);
                },
                centerMode: true,
                className: classNames("__wab_instance", sty.membersCarousel),
                dots: false,
                draggable: true,
                focusOnSelect: true,
                initialSlide: generateStateValueProp($state, [
                  "membersCarousel",
                  "currentSlide"
                ]),
                ref: ref => {
                  $refs["membersCarousel"] = ref;
                },
                rows: 1,
                sliderScopeClassName: sty["membersCarousel__slider"],
                slidesPerRow: 3
              };
              initializeCodeComponentStates(
                $state,
                [
                  {
                    name: "currentSlide",
                    plasmicStateName: "membersCarousel.currentSlide"
                  }
                ],
                [],
                SliderWrapper_Helpers ?? {},
                child$Props
              );

              return (
                <SliderWrapper
                  data-plasmic-name={"membersCarousel"}
                  data-plasmic-override={overrides.membersCarousel}
                  {...child$Props}
                >
                  {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                    (() => {
                      try {
                        return $props.formData?.members || [1];
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return [];
                        }
                        throw e;
                      }
                    })()
                  ).map((__plasmic_item_0, __plasmic_idx_0) => {
                    const currentItem = __plasmic_item_0;
                    const currentIndex = __plasmic_idx_0;
                    return (
                      <div
                        data-plasmic-name={"member2"}
                        data-plasmic-override={overrides.member2}
                        className={classNames(projectcss.all, sty.member2)}
                        key={currentIndex}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__jgmxT
                          )}
                        >
                          <div
                            data-plasmic-name={"office2"}
                            data-plasmic-override={overrides.office2}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.office2
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return currentItem.Office;
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "Data Analyst";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                          <PlasmicImg__
                            data-plasmic-name={"profilePic2"}
                            data-plasmic-override={overrides.profilePic2}
                            alt={""}
                            className={classNames(sty.profilePic2)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"120px"}
                            displayMinHeight={"150px"}
                            displayMinWidth={"0"}
                            displayWidth={"120px"}
                            src={(() => {
                              try {
                                return currentItem["Profile pic"];
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return {
                                    src: "/plasmic/ez_marketing_platform_sacanagem/images/vecteezyUserAccountIconForYourDesignOnly21079672Png.png",
                                    fullWidth: 2551,
                                    fullHeight: 2551,
                                    aspectRatio: undefined
                                  };
                                }
                                throw e;
                              }
                            })()}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___7N2Ne
                            )}
                          >
                            {"Gold"}
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </SliderWrapper>
              );
            })()}
          </div>
        </div>
        <div
          data-plasmic-name={"rateThisAgency"}
          data-plasmic-override={overrides.rateThisAgency}
          className={classNames(projectcss.all, sty.rateThisAgency)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__oKtF
            )}
          >
            {"Rate this agency"}
          </div>
          <div
            data-plasmic-name={"actualData"}
            data-plasmic-override={overrides.actualData}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.actualData
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $props.actualData ?? "";
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "07/2025 - 10/2025";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__fkDj)}>
            <div className={classNames(projectcss.all, sty.freeBox__mzrB0)}>
              <CustomerKnowledgeSvgIcon
                className={classNames(projectcss.all, sty.svg__yzWW)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zbgpc
                )}
              >
                {
                  "Do the clients from that agency know what they're signing up for?\r\n\r"
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nfOwS
                )}
              >
                {
                  "Rate if the clients are well-versed in the available service, getting straight to the point, without any pretensions."
                }
              </div>
              <Modal
                data-plasmic-name={"rate"}
                data-plasmic-override={overrides.rate}
                className={classNames("__wab_instance", sty.rate)}
                content={
                  <div
                    className={classNames(projectcss.all, sty.freeBox__avRxN)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sfaab
                      )}
                    >
                      {
                        "Help other companies know if it's good to work with this agency by leaving a comment."
                      }
                    </div>
                    {(() => {
                      const child$Props = {
                        className: classNames("__wab_instance", sty.comment),
                        onChange: async (...eventArgs: any) => {
                          generateStateOnChangePropForCodeComponents(
                            $state,
                            "value",
                            ["comment", "value"],
                            AntdTextArea_Helpers
                          ).apply(null, eventArgs);
                        },
                        value: generateStateValueProp($state, [
                          "comment",
                          "value"
                        ])
                      };
                      initializeCodeComponentStates(
                        $state,
                        [
                          {
                            name: "value",
                            plasmicStateName: "comment.value"
                          }
                        ],
                        [],
                        AntdTextArea_Helpers ?? {},
                        child$Props
                      );

                      return (
                        <AntdTextArea
                          data-plasmic-name={"comment"}
                          data-plasmic-override={overrides.comment}
                          {...child$Props}
                        />
                      );
                    })()}
                  </div>
                }
                footer={
                  <div
                    className={classNames(projectcss.all, sty.freeBox__hhLrz)}
                  >
                    <Button2
                      data-plasmic-name={"confirmRate"}
                      data-plasmic-override={overrides.confirmRate}
                      color={"muted"}
                      label={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___6YTzS
                          )}
                        >
                          {"Confirm"}
                        </div>
                      }
                      onClick={async event => {
                        const $steps = {};

                        $steps["updateRateIsOpen3"] = true
                          ? (() => {
                              const actionArgs = { args: ["success", "Send"] };
                              return $globalActions[
                                "plasmic-antd5-config-provider.showNotification"
                              ]?.apply(null, [...actionArgs.args]);
                            })()
                          : undefined;
                        if (
                          $steps["updateRateIsOpen3"] != null &&
                          typeof $steps["updateRateIsOpen3"] === "object" &&
                          typeof $steps["updateRateIsOpen3"].then === "function"
                        ) {
                          $steps["updateRateIsOpen3"] =
                            await $steps["updateRateIsOpen3"];
                        }

                        $steps["updateRateIsOpen2"] = true
                          ? (() => {
                              const actionArgs = {
                                customFunction: async () => {
                                  return $props.onSave({
                                    rating: $state.rating?.value,
                                    comment: $state.comment?.value,
                                    type: "company"
                                  });
                                }
                              };
                              return (({ customFunction }) => {
                                return customFunction();
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["updateRateIsOpen2"] != null &&
                          typeof $steps["updateRateIsOpen2"] === "object" &&
                          typeof $steps["updateRateIsOpen2"].then === "function"
                        ) {
                          $steps["updateRateIsOpen2"] =
                            await $steps["updateRateIsOpen2"];
                        }

                        $steps["updateRateIsOpen"] = true
                          ? (() => {
                              const actionArgs = {
                                variable: {
                                  objRoot: $state,
                                  variablePath: ["rate", "isOpen"]
                                },
                                operation: 0,
                                value: false
                              };
                              return (({
                                variable,
                                value,
                                startIndex,
                                deleteCount
                              }) => {
                                if (!variable) {
                                  return;
                                }
                                const { objRoot, variablePath } = variable;

                                $stateSet(objRoot, variablePath, value);
                                return value;
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["updateRateIsOpen"] != null &&
                          typeof $steps["updateRateIsOpen"] === "object" &&
                          typeof $steps["updateRateIsOpen"].then === "function"
                        ) {
                          $steps["updateRateIsOpen"] =
                            await $steps["updateRateIsOpen"];
                        }
                      }}
                      size={"extraSmall"}
                      type={"soft"}
                    />

                    <Button2
                      data-plasmic-name={"button2"}
                      data-plasmic-override={overrides.button2}
                      color={"muted"}
                      label={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___8BlFy
                          )}
                        >
                          {"Cancel"}
                        </div>
                      }
                      onClick={async event => {
                        const $steps = {};

                        $steps["updateRateIsOpen"] = true
                          ? (() => {
                              const actionArgs = {
                                variable: {
                                  objRoot: $state,
                                  variablePath: ["rate", "isOpen"]
                                },
                                operation: 0,
                                value: false
                              };
                              return (({
                                variable,
                                value,
                                startIndex,
                                deleteCount
                              }) => {
                                if (!variable) {
                                  return;
                                }
                                const { objRoot, variablePath } = variable;

                                $stateSet(objRoot, variablePath, value);
                                return value;
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["updateRateIsOpen"] != null &&
                          typeof $steps["updateRateIsOpen"] === "object" &&
                          typeof $steps["updateRateIsOpen"].then === "function"
                        ) {
                          $steps["updateRateIsOpen"] =
                            await $steps["updateRateIsOpen"];
                        }
                      }}
                      size={"extraSmall"}
                      type={"soft"}
                    />
                  </div>
                }
                heading={
                  <h3
                    data-plasmic-name={"h3"}
                    data-plasmic-override={overrides.h3}
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.h3__5uU4L,
                      projectcss.__wab_text,
                      sty.h3
                    )}
                  >
                    {"Rating"}
                  </h3>
                }
                isOpen={generateStateValueProp($state, ["rate", "isOpen"])}
                onOpenChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, ["rate", "isOpen"]).apply(
                    null,
                    eventArgs
                  );

                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
                trigger={
                  <AntdRate
                    data-plasmic-name={"rating"}
                    data-plasmic-override={overrides.rating}
                    allowHalf={true}
                    className={classNames("__wab_instance", sty.rating)}
                    defaultValue={$props.formData?.company_rate ?? 0}
                    onChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "rating",
                        "value"
                      ]).apply(null, eventArgs);
                    }}
                    symbols={
                      <React.Fragment>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fcKx5
                          )}
                        >
                          {"1"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__gPkIv
                          )}
                        >
                          {"2"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__irtmi
                          )}
                        >
                          {"3"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__pBiV
                          )}
                        >
                          {"4"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__i4TlO
                          )}
                        >
                          {"5"}
                        </div>
                      </React.Fragment>
                    }
                    value={generateStateValueProp($state, ["rating", "value"])}
                  />
                }
              />
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__oVlT)}>
              <YourAverageRateSvgIcon
                className={classNames(projectcss.all, sty.svg__vE7Rd)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___1XhF
                )}
              >
                {"Rating received by the agency"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__deBe
                )}
              >
                {
                  "This agency has given your company a rating based on its performance over the last three months."
                }
              </div>
              <AntdRate
                data-plasmic-name={"agencysRate"}
                data-plasmic-override={overrides.agencysRate}
                allowHalf={true}
                className={classNames("__wab_instance", sty.agencysRate)}
                defaultValue={$props.formData?.agency_rate ?? 0}
                disabled={true}
                onChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "agencysRate",
                    "value"
                  ]).apply(null, eventArgs);
                }}
                symbols={
                  <React.Fragment>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ofIrS
                      )}
                    >
                      {"1"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__esVbE
                      )}
                    >
                      {"2"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bvS8
                      )}
                    >
                      {"3"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mE1G4
                      )}
                    >
                      {"4"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__q21Nq
                      )}
                    >
                      {"5"}
                    </div>
                  </React.Fragment>
                }
                value={generateStateValueProp($state, ["agencysRate", "value"])}
              />
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__oFf9F)}>
              <CustomerRatesSvgIcon
                className={classNames(projectcss.all, sty.svg__wlJRy)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___96CK3
                )}
              >
                {"What clients from the agency rated you"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5FpR5
                )}
              >
                {
                  "The clients this agency sent to you rated your service overall over the last three months, with an average of"
                }
              </div>
              <AntdRate
                data-plasmic-name={"customerRated"}
                data-plasmic-override={overrides.customerRated}
                allowHalf={true}
                className={classNames("__wab_instance", sty.customerRated)}
                defaultValue={$props.formData?.customer_rate ?? 0}
                disabled={true}
                onChange={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "customerRated",
                    "value"
                  ]).apply(null, eventArgs);
                }}
                symbols={
                  <React.Fragment>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rIohn
                      )}
                    >
                      {"1"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jk2Pk
                      )}
                    >
                      {"2"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yZgue
                      )}
                    >
                      {"3"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gwv9M
                      )}
                    >
                      {"4"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sbkV3
                      )}
                    >
                      {"5"}
                    </div>
                  </React.Fragment>
                }
                value={generateStateValueProp($state, [
                  "customerRated",
                  "value"
                ])}
              />
            </div>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__jGjhu)}>
          <div className={classNames(projectcss.all, sty.freeBox__fXOz)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jUmDx
              )}
            >
              {"Enter some text"}
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__cZiyh)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5DgHv
                )}
              >
                {"Customer instruction"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tqShr
                )}
              >
                {"Agency rating"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rP55I
                )}
              >
                {"Average rating received"}
              </div>
            </div>
          </div>
          {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
            (() => {
              try {
                return $props.reports || [1];
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return [];
                }
                throw e;
              }
            })()
          ).map((__plasmic_item_0, __plasmic_idx_0) => {
            const currentItem = __plasmic_item_0;
            const currentIndex = __plasmic_idx_0;
            return (
              <div
                data-plasmic-name={"reportRate"}
                data-plasmic-override={overrides.reportRate}
                className={classNames(projectcss.all, sty.reportRate)}
                key={currentIndex}
              >
                <div
                  data-plasmic-name={"reportData"}
                  data-plasmic-override={overrides.reportData}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.reportData
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return currentItem.date;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "07/2025 - 10/2025";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__nGuh)}>
                  {(() => {
                    const child$Props = {
                      allowHalf: true,
                      className: classNames(
                        "__wab_instance",
                        sty.customerInstruction
                      ),
                      defaultValue: currentItem.company,

                      disabled: true,
                      onChange: async (...eventArgs: any) => {
                        generateStateOnChangeProp($state, [
                          "customerInstruction",
                          __plasmic_idx_0,
                          "value"
                        ]).apply(null, eventArgs);
                      },
                      symbols: (
                        <React.Fragment>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__xAuK
                            )}
                          >
                            {"1"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gd5ZC
                            )}
                          >
                            {"2"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ppfnK
                            )}
                          >
                            {"3"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___1ZTpL
                            )}
                          >
                            {"4"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___5ASdZ
                            )}
                          >
                            {"5"}
                          </div>
                        </React.Fragment>
                      ),
                      value: generateStateValueProp($state, [
                        "customerInstruction",
                        __plasmic_idx_0,
                        "value"
                      ])
                    };
                    initializeCodeComponentStates(
                      $state,
                      [
                        {
                          name: "value",
                          plasmicStateName: "customerInstruction[].value"
                        }
                      ],
                      [__plasmic_idx_0],
                      undefined ?? {},
                      child$Props
                    );
                    initializePlasmicStates(
                      $state,
                      [
                        {
                          name: "customerInstruction[].value",
                          initFunc: ({ $props, $state, $queries, $q }) =>
                            currentItem.company
                        }
                      ],
                      [__plasmic_idx_0]
                    );
                    return (
                      <AntdRate
                        data-plasmic-name={"customerInstruction"}
                        data-plasmic-override={overrides.customerInstruction}
                        {...child$Props}
                      />
                    );
                  })()}
                  {(() => {
                    const child$Props = {
                      allowHalf: true,
                      className: classNames("__wab_instance", sty.agencyRate),
                      defaultValue: currentItem.agency,

                      disabled: true,
                      onChange: async (...eventArgs: any) => {
                        generateStateOnChangeProp($state, [
                          "agencyRate",
                          __plasmic_idx_0,
                          "value"
                        ]).apply(null, eventArgs);
                      },
                      symbols: (
                        <React.Fragment>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__oUUzh
                            )}
                          >
                            {"1"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__q2IDq
                            )}
                          >
                            {"2"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__khCaJ
                            )}
                          >
                            {"3"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__sbU0J
                            )}
                          >
                            {"4"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__jyBfs
                            )}
                          >
                            {"5"}
                          </div>
                        </React.Fragment>
                      ),
                      value: generateStateValueProp($state, [
                        "agencyRate",
                        __plasmic_idx_0,
                        "value"
                      ])
                    };
                    initializeCodeComponentStates(
                      $state,
                      [
                        {
                          name: "value",
                          plasmicStateName: "agencyRate[].value"
                        }
                      ],
                      [__plasmic_idx_0],
                      undefined ?? {},
                      child$Props
                    );
                    initializePlasmicStates(
                      $state,
                      [
                        {
                          name: "agencyRate[].value",
                          initFunc: ({ $props, $state, $queries, $q }) =>
                            currentItem.agency
                        }
                      ],
                      [__plasmic_idx_0]
                    );
                    return (
                      <AntdRate
                        data-plasmic-name={"agencyRate"}
                        data-plasmic-override={overrides.agencyRate}
                        {...child$Props}
                      />
                    );
                  })()}
                  {(() => {
                    const child$Props = {
                      allowHalf: true,
                      className: classNames(
                        "__wab_instance",
                        sty.averageRatingReceived
                      ),
                      defaultValue: currentItem.customer,

                      disabled: true,
                      onChange: async (...eventArgs: any) => {
                        generateStateOnChangeProp($state, [
                          "averageRatingReceived",
                          __plasmic_idx_0,
                          "value"
                        ]).apply(null, eventArgs);
                      },
                      symbols: (
                        <React.Fragment>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___0D6H
                            )}
                          >
                            {"1"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__wHjan
                            )}
                          >
                            {"2"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__yA4B
                            )}
                          >
                            {"3"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___65WzR
                            )}
                          >
                            {"4"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__xaoUh
                            )}
                          >
                            {"5"}
                          </div>
                        </React.Fragment>
                      ),
                      value: generateStateValueProp($state, [
                        "averageRatingReceived",
                        __plasmic_idx_0,
                        "value"
                      ])
                    };
                    initializeCodeComponentStates(
                      $state,
                      [
                        {
                          name: "value",
                          plasmicStateName: "averageRatingReceived[].value"
                        }
                      ],
                      [__plasmic_idx_0],
                      undefined ?? {},
                      child$Props
                    );
                    initializePlasmicStates(
                      $state,
                      [
                        {
                          name: "averageRatingReceived[].value",
                          initFunc: ({ $props, $state, $queries, $q }) =>
                            currentItem.customer
                        }
                      ],
                      [__plasmic_idx_0]
                    );
                    return (
                      <AntdRate
                        data-plasmic-name={"averageRatingReceived"}
                        data-plasmic-override={overrides.averageRatingReceived}
                        {...child$Props}
                      />
                    );
                  })()}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "topBarAuto",
    "navigationBar",
    "account2",
    "button",
    "container3",
    "communityLogo2",
    "type2",
    "communityName2",
    "membersCarousel",
    "member2",
    "office2",
    "profilePic2",
    "rateThisAgency",
    "actualData",
    "rate",
    "rating",
    "h3",
    "comment",
    "confirmRate",
    "button2",
    "agencysRate",
    "customerRated",
    "reportRate",
    "reportData",
    "customerInstruction",
    "agencyRate",
    "averageRatingReceived"
  ],
  topBarAuto: ["topBarAuto", "navigationBar", "account2", "button"],
  navigationBar: ["navigationBar"],
  account2: ["account2", "button"],
  button: ["button"],
  container3: [
    "container3",
    "communityLogo2",
    "type2",
    "communityName2",
    "membersCarousel",
    "member2",
    "office2",
    "profilePic2"
  ],
  communityLogo2: ["communityLogo2"],
  type2: ["type2"],
  communityName2: ["communityName2"],
  membersCarousel: ["membersCarousel", "member2", "office2", "profilePic2"],
  member2: ["member2", "office2", "profilePic2"],
  office2: ["office2"],
  profilePic2: ["profilePic2"],
  rateThisAgency: [
    "rateThisAgency",
    "actualData",
    "rate",
    "rating",
    "h3",
    "comment",
    "confirmRate",
    "button2",
    "agencysRate",
    "customerRated"
  ],
  actualData: ["actualData"],
  rate: ["rate", "rating", "h3", "comment", "confirmRate", "button2"],
  rating: ["rating"],
  h3: ["h3"],
  comment: ["comment"],
  confirmRate: ["confirmRate"],
  button2: ["button2"],
  agencysRate: ["agencysRate"],
  customerRated: ["customerRated"],
  reportRate: [
    "reportRate",
    "reportData",
    "customerInstruction",
    "agencyRate",
    "averageRatingReceived"
  ],
  reportData: ["reportData"],
  customerInstruction: ["customerInstruction"],
  agencyRate: ["agencyRate"],
  averageRatingReceived: ["averageRatingReceived"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  topBarAuto: "div";
  navigationBar: typeof NavigationBar;
  account2: typeof AntdDropdown;
  button: typeof AntdButton;
  container3: "div";
  communityLogo2: typeof PlasmicImg__;
  type2: "svg";
  communityName2: "div";
  membersCarousel: typeof SliderWrapper;
  member2: "div";
  office2: "div";
  profilePic2: typeof PlasmicImg__;
  rateThisAgency: "div";
  actualData: "div";
  rate: typeof Modal;
  rating: typeof AntdRate;
  h3: "h3";
  comment: typeof AntdTextArea;
  confirmRate: typeof Button2;
  button2: typeof Button2;
  agencysRate: typeof AntdRate;
  customerRated: typeof AntdRate;
  reportRate: "div";
  reportData: "div";
  customerInstruction: typeof AntdRate;
  agencyRate: typeof AntdRate;
  averageRatingReceived: typeof AntdRate;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCRateACommunitie__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCRateACommunitie__VariantsArgs;
    args?: PlasmicCRateACommunitie__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicCRateACommunitie__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicCRateACommunitie__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCRateACommunitie__ArgProps,
          internalVariantPropNames: PlasmicCRateACommunitie__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCRateACommunitie__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCRateACommunitie";
  } else {
    func.displayName = `PlasmicCRateACommunitie.${nodeName}`;
  }
  return func;
}

export const PlasmicCRateACommunitie = Object.assign(
  // Top-level PlasmicCRateACommunitie renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    topBarAuto: makeNodeComponent("topBarAuto"),
    navigationBar: makeNodeComponent("navigationBar"),
    account2: makeNodeComponent("account2"),
    button: makeNodeComponent("button"),
    container3: makeNodeComponent("container3"),
    communityLogo2: makeNodeComponent("communityLogo2"),
    type2: makeNodeComponent("type2"),
    communityName2: makeNodeComponent("communityName2"),
    membersCarousel: makeNodeComponent("membersCarousel"),
    member2: makeNodeComponent("member2"),
    office2: makeNodeComponent("office2"),
    profilePic2: makeNodeComponent("profilePic2"),
    rateThisAgency: makeNodeComponent("rateThisAgency"),
    actualData: makeNodeComponent("actualData"),
    rate: makeNodeComponent("rate"),
    rating: makeNodeComponent("rating"),
    h3: makeNodeComponent("h3"),
    comment: makeNodeComponent("comment"),
    confirmRate: makeNodeComponent("confirmRate"),
    button2: makeNodeComponent("button2"),
    agencysRate: makeNodeComponent("agencysRate"),
    customerRated: makeNodeComponent("customerRated"),
    reportRate: makeNodeComponent("reportRate"),
    reportData: makeNodeComponent("reportData"),
    customerInstruction: makeNodeComponent("customerInstruction"),
    agencyRate: makeNodeComponent("agencyRate"),
    averageRatingReceived: makeNodeComponent("averageRatingReceived"),

    // Metadata about props expected for PlasmicCRateACommunitie
    internalVariantProps: PlasmicCRateACommunitie__VariantProps,
    internalArgProps: PlasmicCRateACommunitie__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/c-rate-community",
      pagePath: "/c-rate-community",
      params: {},
      query: {}
    })
  }
);

export default PlasmicCRateACommunitie;
/* prettier-ignore-end */
