/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5uU4LbmmcY9V8oBke7M62e
// Component: _c19kcCNYVI5

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import { AntdDropdown } from "@plasmicpkgs/antd5/skinny/registerDropdown";
import { AntdMenuItem } from "@plasmicpkgs/antd5/skinny/registerMenu";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { AntdRate } from "@plasmicpkgs/antd5/skinny/registerRate";
import LoginButton from "../../LoginButton"; // plasmic-import: DYHdsjcJLpSq/component
import Modal from "../../Modal"; // plasmic-import: 2mIwXeE-_Psc/component
import { AntdTextArea } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdTextArea_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import Button2 from "../../Button2"; // plasmic-import: t1SFzVEz5RlV/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 5uU4LbmmcY9V8oBke7M62e/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 5uU4LbmmcY9V8oBke7M62e/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 5uU4LbmmcY9V8oBke7M62e/projectcss
import sty from "./PlasmicARatingCompanies.module.css"; // plasmic-import: _c19kcCNYVI5/css

import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: 2MH9wfBMgppQ/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: _eklczUQ9Bdt/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: 6guEK3lWtsZR/icon
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: y4E8J3i62sTp/icon
import IlustrgatuSvgIcon from "./icons/PlasmicIcon__IlustrgatuSvg"; // plasmic-import: 0rpJDt-WBeXQ/icon
import GlobalSvgrepoComSvgIcon from "./icons/PlasmicIcon__GlobalSvgrepoComSvg"; // plasmic-import: ilpCvDub8cvP/icon
import YourAverageRateSvgIcon from "./icons/PlasmicIcon__YourAverageRateSvg"; // plasmic-import: 182P-Ny0NQeA/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: l4RREmL1A-vM/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: qJDdQLGS2RlC/icon
import CustomerKnowledgeSvgIcon from "./icons/PlasmicIcon__CustomerKnowledgeSvg"; // plasmic-import: YMJJ4lfeZ6ds/icon
import CustomerRatesSvgIcon from "./icons/PlasmicIcon__CustomerRatesSvg"; // plasmic-import: ayP013CUNl9_/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicARatingCompanies__VariantMembers = {};
export type PlasmicARatingCompanies__VariantsArgs = {};
type VariantPropType = keyof PlasmicARatingCompanies__VariantsArgs;
export const PlasmicARatingCompanies__VariantProps =
  new Array<VariantPropType>();

export type PlasmicARatingCompanies__ArgsType = {};
type ArgPropType = keyof PlasmicARatingCompanies__ArgsType;
export const PlasmicARatingCompanies__ArgProps = new Array<ArgPropType>();

export type PlasmicARatingCompanies__OverridesType = {
  root?: Flex__<"div">;
  topBar?: Flex__<"div">;
  navigationBar?: Flex__<typeof NavigationBar>;
  account?: Flex__<typeof AntdDropdown>;
  button?: Flex__<typeof AntdButton>;
  countainer1?: Flex__<"div">;
  companyLogo?: Flex__<typeof PlasmicImg__>;
  companyName?: Flex__<"div">;
  companyType?: Flex__<"div">;
  averageRate?: Flex__<typeof AntdRate>;
  rateSum?: Flex__<"div">;
  area?: Flex__<"div">;
  subArea?: Flex__<"div">;
  location?: Flex__<"div">;
  foundationDate?: Flex__<"div">;
  goalsSum?: Flex__<"div">;
  partnershipLink?: Flex__<typeof LoginButton>;
  companyTagline?: Flex__<"div">;
  linkedIn?: Flex__<"a"> & Partial<LinkProps>;
  instagram?: Flex__<"a"> & Partial<LinkProps>;
  x?: Flex__<"a"> & Partial<LinkProps>;
  website?: Flex__<"a"> & Partial<LinkProps>;
  rateThisCompany?: Flex__<"div">;
  actualData?: Flex__<"div">;
  rate?: Flex__<typeof Modal>;
  rating?: Flex__<typeof AntdRate>;
  h3?: Flex__<"h3">;
  comment?: Flex__<typeof AntdTextArea>;
  confirmRate?: Flex__<typeof Button2>;
  button2?: Flex__<typeof Button2>;
  companyRated?: Flex__<typeof AntdRate>;
  rateSum2?: Flex__<"div">;
  customerRated?: Flex__<typeof AntdRate>;
  rateSum3?: Flex__<"div">;
  reportRate?: Flex__<"div">;
  reportData?: Flex__<"div">;
  companyRate?: Flex__<typeof AntdRate>;
  customerInstruction?: Flex__<typeof AntdRate>;
  averageRatingReceived?: Flex__<typeof AntdRate>;
};

export interface DefaultARatingCompaniesProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicARatingCompanies__RenderFunc(props: {
  variants: PlasmicARatingCompanies__VariantsArgs;
  args: PlasmicARatingCompanies__ArgsType;
  overrides: PlasmicARatingCompanies__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "averageRate.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => 5
      },
      {
        path: "companyRate.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "customerInstruction.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "averageRatingReceived.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "rate.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "rating.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "comment.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdTextArea_Helpers)
      },
      {
        path: "companyRated.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "customerRated.value",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"topBar"}
            data-plasmic-override={overrides.topBar}
            className={classNames(projectcss.all, sty.topBar)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__s0Fpo)}>
              <div className={classNames(projectcss.all, sty.freeBox__qFcIz)}>
                <NavigationBar
                  data-plasmic-name={"navigationBar"}
                  data-plasmic-override={overrides.navigationBar}
                  brand={
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__bgUqp
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__oWIcP)}
                        displayHeight={"30px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={{
                          src: "/plasmic/ez_marketing_platform_sacanagem/images/ezSvg2.svg",
                          fullWidth: 60,
                          fullHeight: 31,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                  }
                  className={classNames("__wab_instance", sty.navigationBar)}
                  closeButton={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__ax5U5)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      src={"https://static1.plasmic.app/close.svg"}
                    />
                  }
                  itemsGap={8}
                  menuItems={
                    <React.Fragment>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__eVtEs
                        )}
                        component={Link}
                        href={`/a-community-dashboard`}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        {"Community Dashboard"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link___4Br6B
                        )}
                        component={Link}
                        href={`/a-service-dashboard`}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        {"Service\nDashboard"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__ehh2F
                        )}
                        component={Link}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        {"Market\nTrends"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__pishz
                        )}
                        component={Link}
                        href={`/a-find-a-business`}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        {"Find a \nbusiness"}
                      </PlasmicLink__>
                    </React.Fragment>
                  }
                  openButton={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__cm5Vk)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      height={``}
                      src={"https://static1.plasmic.app/menu.svg"}
                      width={``}
                    />
                  }
                  responsiveBreakpoint={768}
                />

                <AntdDropdown
                  data-plasmic-name={"account"}
                  data-plasmic-override={overrides.account}
                  className={classNames("__wab_instance", sty.account)}
                  dropdownMenuScopeClassName={sty["account__dropdownMenu"]}
                  menuItems={() => (
                    <React.Fragment>
                      <AntdMenuItem
                        className={classNames(
                          "__wab_instance",
                          sty.menuItem__aUjdv
                        )}
                        key={"menu-item-1"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__jPbtV
                          )}
                        >
                          {"Menu item"}
                        </div>
                      </AntdMenuItem>
                      <AntdMenuItem
                        className={classNames(
                          "__wab_instance",
                          sty.menuItem__xmX9
                        )}
                        key={"menu-item-2"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__lkDaI
                          )}
                        >
                          {"Menu item"}
                        </div>
                      </AntdMenuItem>
                    </React.Fragment>
                  )}
                  menuItemsJson={(() => {
                    const __composite = [
                      { type: null, label: null, children: null },
                      {
                        type: null,
                        value: "action1",
                        label: null,
                        children: null
                      },
                      {
                        type: null,
                        value: "action2",
                        label: null,
                        onClick: null
                      }
                    ];
                    __composite["0"]["type"] = "group";
                    __composite["0"]["label"] = "User";
                    __composite["0"]["children"] = (() => {
                      const __composite = [
                        { type: "item", label: null, onClick: null },
                        { type: "item", label: null, onClick: null },
                        { type: null }
                      ];
                      __composite["0"]["label"] = "Profile";
                      __composite["1"]["label"] = "Edit profile";
                      __composite["2"]["type"] = "divider";
                      return __composite;
                    })();
                    __composite["1"]["type"] = "group";
                    __composite["1"]["label"] = "Account";
                    __composite["1"]["children"] = (() => {
                      const __composite = [
                        { type: "item", label: null, onClick: null },
                        { type: "item", label: null, onClick: null },
                        { type: null }
                      ];
                      __composite["0"]["label"] = "Settings & Privacy";
                      __composite["1"]["label"] = "Help";
                      __composite["2"]["type"] = "divider";
                      return __composite;
                    })();
                    __composite["2"]["type"] = "item";
                    __composite["2"]["label"] = "Sign out";
                    return __composite;
                  })()}
                  trigger={"hover"}
                  useMenuItemsSlot={false}
                >
                  <AntdButton
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames("__wab_instance", sty.button)}
                    target={true}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__gw1Sn)}
                      displayHeight={"30px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"30px"}
                      loading={"lazy"}
                    />
                  </AntdButton>
                </AntdDropdown>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"countainer1"}
            data-plasmic-override={overrides.countainer1}
            className={classNames(projectcss.all, sty.countainer1)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__gioPt)}>
              <PlasmicImg__
                data-plasmic-name={"companyLogo"}
                data-plasmic-override={overrides.companyLogo}
                alt={""}
                className={classNames(sty.companyLogo)}
                displayHeight={"100px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100px"}
                loading={"lazy"}
              />

              <div className={classNames(projectcss.all, sty.freeBox__agjeg)}>
                <div className={classNames(projectcss.all, sty.freeBox__iy9Ys)}>
                  <div
                    data-plasmic-name={"companyName"}
                    data-plasmic-override={overrides.companyName}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.companyName
                    )}
                  >
                    {"Company"}
                  </div>
                  <div
                    data-plasmic-name={"companyType"}
                    data-plasmic-override={overrides.companyType}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.companyType
                    )}
                  >
                    {"INC"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__iaska)}
                  >
                    <AntdRate
                      data-plasmic-name={"averageRate"}
                      data-plasmic-override={overrides.averageRate}
                      allowHalf={true}
                      className={classNames("__wab_instance", sty.averageRate)}
                      defaultValue={5}
                      disabled={true}
                      multiCharacter={false}
                      onChange={async (...eventArgs: any) => {
                        generateStateOnChangeProp($state, [
                          "averageRate",
                          "value"
                        ]).apply(null, eventArgs);
                      }}
                      symbols={
                        <React.Fragment>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__vEmy0
                            )}
                          >
                            {"1"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___0CmjK
                            )}
                          >
                            {"2"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__fTy2V
                            )}
                          >
                            {"3"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gZxzE
                            )}
                          >
                            {"4"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___6F3Sn
                            )}
                          >
                            {"5"}
                          </div>
                        </React.Fragment>
                      }
                      value={generateStateValueProp($state, [
                        "averageRate",
                        "value"
                      ])}
                    />

                    <div
                      data-plasmic-name={"rateSum"}
                      data-plasmic-override={overrides.rateSum}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.rateSum
                      )}
                    >
                      {"(50)"}
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__s4NnL)}>
                  <div
                    data-plasmic-name={"area"}
                    data-plasmic-override={overrides.area}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.area
                    )}
                  >
                    {"Niche"}
                  </div>
                  <div
                    data-plasmic-name={"subArea"}
                    data-plasmic-override={overrides.subArea}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.subArea
                    )}
                  >
                    {"Subniche"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"location"}
                  data-plasmic-override={overrides.location}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.location
                  )}
                >
                  {"New York"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___7YRPv)}>
                <div className={classNames(projectcss.all, sty.freeBox__g98B)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oc0P
                    )}
                  >
                    {"Since"}
                  </div>
                  <div
                    data-plasmic-name={"foundationDate"}
                    data-plasmic-override={overrides.foundationDate}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.foundationDate
                    )}
                  >
                    {"Botstrap"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__jUicy)}>
                  <div
                    data-plasmic-name={"goalsSum"}
                    data-plasmic-override={overrides.goalsSum}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.goalsSum
                    )}
                  >
                    {"80"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__c65C0
                    )}
                  >
                    {"Goals achieved"}
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__epfG)}>
                <LoginButton
                  data-plasmic-name={"partnershipLink"}
                  data-plasmic-override={overrides.partnershipLink}
                  className={classNames("__wab_instance", sty.partnershipLink)}
                  shape={"rounded"}
                  size={"compact"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sohyj
                    )}
                  >
                    {"Partnership Link"}
                  </div>
                </LoginButton>
              </div>
            </div>
            <div
              data-plasmic-name={"companyTagline"}
              data-plasmic-override={overrides.companyTagline}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.companyTagline
              )}
            >
              {"Startup tagline"}
            </div>
            <div className={classNames(projectcss.all, sty.freeBox___5Cesx)}>
              <div className={classNames(projectcss.all, sty.freeBox__in4Mk)}>
                <Icon4Icon
                  className={classNames(projectcss.all, sty.svg__pzRxf)}
                  role={"img"}
                />

                <PlasmicLink__
                  data-plasmic-name={"linkedIn"}
                  data-plasmic-override={overrides.linkedIn}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.linkedIn
                  )}
                  component={Link}
                  href={"https://www.plasmic.app/"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {"Linkedin"}
                </PlasmicLink__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__fWvIp)}>
                <Icon6Icon
                  className={classNames(projectcss.all, sty.svg__b1Eo3)}
                  role={"img"}
                />

                <PlasmicLink__
                  data-plasmic-name={"instagram"}
                  data-plasmic-override={overrides.instagram}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.instagram
                  )}
                  component={Link}
                  href={"https://www.plasmic.app/"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {"Instagram"}
                </PlasmicLink__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___6PjyS)}>
                <IlustrgatuSvgIcon
                  className={classNames(projectcss.all, sty.svg__jl8Bk)}
                  role={"img"}
                />

                <PlasmicLink__
                  data-plasmic-name={"x"}
                  data-plasmic-override={overrides.x}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.x
                  )}
                  component={Link}
                  href={"https://www.plasmic.app/"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {"X"}
                </PlasmicLink__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__dkDbG)}>
                <GlobalSvgrepoComSvgIcon
                  className={classNames(projectcss.all, sty.svg__yCY)}
                  role={"img"}
                />

                <PlasmicLink__
                  data-plasmic-name={"website"}
                  data-plasmic-override={overrides.website}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.website
                  )}
                  component={Link}
                  href={"https://www.plasmic.app/"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {"Website"}
                </PlasmicLink__>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"rateThisCompany"}
            data-plasmic-override={overrides.rateThisCompany}
            className={classNames(projectcss.all, sty.rateThisCompany)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__wwfqx
              )}
            >
              {"Rate this company"}
            </div>
            <div
              data-plasmic-name={"actualData"}
              data-plasmic-override={overrides.actualData}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.actualData
              )}
            >
              {"07/2025 - 10/2025"}
            </div>
            <div className={classNames(projectcss.all, sty.freeBox___5Ihq)}>
              <div className={classNames(projectcss.all, sty.freeBox__mHw5M)}>
                <YourAverageRateSvgIcon
                  className={classNames(projectcss.all, sty.svg___6Guhv)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2Db84
                  )}
                >
                  {"Rate this company"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__krl66
                  )}
                >
                  {
                    "Rate your overall experience with this company, the conversion rate, commissions received, and the company's growth plan"
                  }
                </div>
                <Modal
                  data-plasmic-name={"rate"}
                  data-plasmic-override={overrides.rate}
                  className={classNames("__wab_instance", sty.rate)}
                  content={
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___85JGg
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ibHi
                        )}
                      >
                        {
                          "Leave a comment, try to share your experience and your expectations or disappointments."
                        }
                      </div>
                      {(() => {
                        const child$Props = {
                          className: classNames("__wab_instance", sty.comment),
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["comment", "value"],
                              AntdTextArea_Helpers
                            ).apply(null, eventArgs);
                          },
                          value: generateStateValueProp($state, [
                            "comment",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "comment.value"
                            }
                          ],
                          [],
                          AntdTextArea_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <AntdTextArea
                            data-plasmic-name={"comment"}
                            data-plasmic-override={overrides.comment}
                            {...child$Props}
                          />
                        );
                      })()}
                    </div>
                  }
                  footer={
                    <div
                      className={classNames(projectcss.all, sty.freeBox__h99YE)}
                    >
                      <Button2
                        data-plasmic-name={"confirmRate"}
                        data-plasmic-override={overrides.confirmRate}
                        color={"muted"}
                        label={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__su1SA
                            )}
                          >
                            {"Confirm"}
                          </div>
                        }
                        onClick={async event => {
                          const $steps = {};

                          $steps["updateModalIsOpen"] = true
                            ? (() => {
                                const actionArgs = {
                                  variable: {
                                    objRoot: $state,
                                    variablePath: ["rate", "isOpen"]
                                  },
                                  operation: 0,
                                  value: false
                                };
                                return (({
                                  variable,
                                  value,
                                  startIndex,
                                  deleteCount
                                }) => {
                                  if (!variable) {
                                    return;
                                  }
                                  const { objRoot, variablePath } = variable;

                                  $stateSet(objRoot, variablePath, value);
                                  return value;
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["updateModalIsOpen"] != null &&
                            typeof $steps["updateModalIsOpen"] === "object" &&
                            typeof $steps["updateModalIsOpen"].then ===
                              "function"
                          ) {
                            $steps["updateModalIsOpen"] =
                              await $steps["updateModalIsOpen"];
                          }
                        }}
                        size={"extraSmall"}
                        type={"soft"}
                      />

                      <Button2
                        data-plasmic-name={"button2"}
                        data-plasmic-override={overrides.button2}
                        color={"muted"}
                        label={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__dxdkT
                            )}
                          >
                            {"Cancel"}
                          </div>
                        }
                        onClick={async event => {
                          const $steps = {};

                          $steps["updateModalIsOpen"] = true
                            ? (() => {
                                const actionArgs = {
                                  variable: {
                                    objRoot: $state,
                                    variablePath: ["rate", "isOpen"]
                                  },
                                  operation: 0,
                                  value: false
                                };
                                return (({
                                  variable,
                                  value,
                                  startIndex,
                                  deleteCount
                                }) => {
                                  if (!variable) {
                                    return;
                                  }
                                  const { objRoot, variablePath } = variable;

                                  $stateSet(objRoot, variablePath, value);
                                  return value;
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["updateModalIsOpen"] != null &&
                            typeof $steps["updateModalIsOpen"] === "object" &&
                            typeof $steps["updateModalIsOpen"].then ===
                              "function"
                          ) {
                            $steps["updateModalIsOpen"] =
                              await $steps["updateModalIsOpen"];
                          }
                        }}
                        size={"extraSmall"}
                        type={"soft"}
                      />
                    </div>
                  }
                  heading={
                    <h3
                      data-plasmic-name={"h3"}
                      data-plasmic-override={overrides.h3}
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3
                      )}
                    >
                      {"Rating"}
                    </h3>
                  }
                  isOpen={generateStateValueProp($state, ["rate", "isOpen"])}
                  onOpenChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, ["rate", "isOpen"]).apply(
                      null,
                      eventArgs
                    );

                    if (
                      eventArgs.length > 1 &&
                      eventArgs[1] &&
                      eventArgs[1]._plasmic_state_init_
                    ) {
                      return;
                    }
                  }}
                  trigger={
                    <AntdRate
                      data-plasmic-name={"rating"}
                      data-plasmic-override={overrides.rating}
                      allowHalf={true}
                      className={classNames("__wab_instance", sty.rating)}
                      onChange={async (...eventArgs: any) => {
                        generateStateOnChangeProp($state, [
                          "rating",
                          "value"
                        ]).apply(null, eventArgs);
                      }}
                      symbols={
                        <React.Fragment>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__m6A30
                            )}
                          >
                            {"1"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__fdK06
                            )}
                          >
                            {"2"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__zrDzR
                            )}
                          >
                            {"3"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__sMzF5
                            )}
                          >
                            {"4"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__g8Mns
                            )}
                          >
                            {"5"}
                          </div>
                        </React.Fragment>
                      }
                      value={generateStateValueProp($state, [
                        "rating",
                        "value"
                      ])}
                    />
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__sFXtN)}>
                <CustomerKnowledgeSvgIcon
                  className={classNames(projectcss.all, sty.svg__l1Zui)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__y6JM
                  )}
                >
                  {"Client Awareness Evaluation"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nzG5N
                  )}
                >
                  {
                    "This company evaluated how well-informed the clients referred by your agency were about its services and operations before engaging with them"
                  }
                </div>
                <AntdRate
                  data-plasmic-name={"companyRated"}
                  data-plasmic-override={overrides.companyRated}
                  allowHalf={true}
                  className={classNames("__wab_instance", sty.companyRated)}
                  disabled={true}
                  onChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "companyRated",
                      "value"
                    ]).apply(null, eventArgs);
                  }}
                  symbols={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__cAp6A
                        )}
                      >
                        {"1"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__eX32A
                        )}
                      >
                        {"2"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hr39L
                        )}
                      >
                        {"3"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__h27G
                        )}
                      >
                        {"4"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qf9Td
                        )}
                      >
                        {"5"}
                      </div>
                    </React.Fragment>
                  }
                  value={generateStateValueProp($state, [
                    "companyRated",
                    "value"
                  ])}
                />

                <div
                  data-plasmic-name={"rateSum2"}
                  data-plasmic-override={overrides.rateSum2}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.rateSum2
                  )}
                >
                  {"(50)"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__dDnmB)}>
                <CustomerRatesSvgIcon
                  className={classNames(projectcss.all, sty.svg__hMhl)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zBll
                  )}
                >
                  {"How clients rated this company"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ars2H
                  )}
                >
                  {
                    "You sent some clients to this company in the last month. This is the average of their ratings"
                  }
                </div>
                <AntdRate
                  data-plasmic-name={"customerRated"}
                  data-plasmic-override={overrides.customerRated}
                  allowHalf={true}
                  className={classNames("__wab_instance", sty.customerRated)}
                  disabled={true}
                  onChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "customerRated",
                      "value"
                    ]).apply(null, eventArgs);
                  }}
                  symbols={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wJ2Xy
                        )}
                      >
                        {"1"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zn8Sw
                        )}
                      >
                        {"2"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wRg5N
                        )}
                      >
                        {"3"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___2WbDt
                        )}
                      >
                        {"4"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__cP4
                        )}
                      >
                        {"5"}
                      </div>
                    </React.Fragment>
                  }
                  value={generateStateValueProp($state, [
                    "customerRated",
                    "value"
                  ])}
                />

                <div
                  data-plasmic-name={"rateSum3"}
                  data-plasmic-override={overrides.rateSum3}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.rateSum3
                  )}
                >
                  {"(50)"}
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__dpv4U)}>
            <div className={classNames(projectcss.all, sty.freeBox__seYt0)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zd7Wh
                )}
              >
                {"Enter some text"}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__ecaYu)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4MG3S
                  )}
                >
                  {"Company rating"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___955Sx
                  )}
                >
                  {"Customer instruction"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__txVNj
                  )}
                >
                  {"Average rating received"}
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"reportRate"}
              data-plasmic-override={overrides.reportRate}
              className={classNames(projectcss.all, sty.reportRate)}
            >
              <div
                data-plasmic-name={"reportData"}
                data-plasmic-override={overrides.reportData}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.reportData
                )}
              >
                {"07/2025 - 10/2025"}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__ttzSh)}>
                <AntdRate
                  data-plasmic-name={"companyRate"}
                  data-plasmic-override={overrides.companyRate}
                  allowHalf={true}
                  className={classNames("__wab_instance", sty.companyRate)}
                  disabled={true}
                  onChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "companyRate",
                      "value"
                    ]).apply(null, eventArgs);
                  }}
                  symbols={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gWw86
                        )}
                      >
                        {"1"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__crhHh
                        )}
                      >
                        {"2"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mq2Kn
                        )}
                      >
                        {"3"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bImEb
                        )}
                      >
                        {"4"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ifzV6
                        )}
                      >
                        {"5"}
                      </div>
                    </React.Fragment>
                  }
                  value={generateStateValueProp($state, [
                    "companyRate",
                    "value"
                  ])}
                />

                <AntdRate
                  data-plasmic-name={"customerInstruction"}
                  data-plasmic-override={overrides.customerInstruction}
                  allowHalf={true}
                  className={classNames(
                    "__wab_instance",
                    sty.customerInstruction
                  )}
                  disabled={true}
                  onChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "customerInstruction",
                      "value"
                    ]).apply(null, eventArgs);
                  }}
                  symbols={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kzwJ3
                        )}
                      >
                        {"1"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___2Psdr
                        )}
                      >
                        {"2"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___44DNe
                        )}
                      >
                        {"3"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uPJby
                        )}
                      >
                        {"4"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___1ZORy
                        )}
                      >
                        {"5"}
                      </div>
                    </React.Fragment>
                  }
                  value={generateStateValueProp($state, [
                    "customerInstruction",
                    "value"
                  ])}
                />

                <AntdRate
                  data-plasmic-name={"averageRatingReceived"}
                  data-plasmic-override={overrides.averageRatingReceived}
                  allowHalf={true}
                  className={classNames(
                    "__wab_instance",
                    sty.averageRatingReceived
                  )}
                  disabled={true}
                  onChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "averageRatingReceived",
                      "value"
                    ]).apply(null, eventArgs);
                  }}
                  symbols={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___5ZaCa
                        )}
                      >
                        {"1"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mlu9G
                        )}
                      >
                        {"2"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__v1Skh
                        )}
                      >
                        {"3"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__loj5E
                        )}
                      >
                        {"4"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oCdca
                        )}
                      >
                        {"5"}
                      </div>
                    </React.Fragment>
                  }
                  value={generateStateValueProp($state, [
                    "averageRatingReceived",
                    "value"
                  ])}
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "topBar",
    "navigationBar",
    "account",
    "button",
    "countainer1",
    "companyLogo",
    "companyName",
    "companyType",
    "averageRate",
    "rateSum",
    "area",
    "subArea",
    "location",
    "foundationDate",
    "goalsSum",
    "partnershipLink",
    "companyTagline",
    "linkedIn",
    "instagram",
    "x",
    "website",
    "rateThisCompany",
    "actualData",
    "rate",
    "rating",
    "h3",
    "comment",
    "confirmRate",
    "button2",
    "companyRated",
    "rateSum2",
    "customerRated",
    "rateSum3",
    "reportRate",
    "reportData",
    "companyRate",
    "customerInstruction",
    "averageRatingReceived"
  ],
  topBar: ["topBar", "navigationBar", "account", "button"],
  navigationBar: ["navigationBar"],
  account: ["account", "button"],
  button: ["button"],
  countainer1: [
    "countainer1",
    "companyLogo",
    "companyName",
    "companyType",
    "averageRate",
    "rateSum",
    "area",
    "subArea",
    "location",
    "foundationDate",
    "goalsSum",
    "partnershipLink",
    "companyTagline",
    "linkedIn",
    "instagram",
    "x",
    "website"
  ],
  companyLogo: ["companyLogo"],
  companyName: ["companyName"],
  companyType: ["companyType"],
  averageRate: ["averageRate"],
  rateSum: ["rateSum"],
  area: ["area"],
  subArea: ["subArea"],
  location: ["location"],
  foundationDate: ["foundationDate"],
  goalsSum: ["goalsSum"],
  partnershipLink: ["partnershipLink"],
  companyTagline: ["companyTagline"],
  linkedIn: ["linkedIn"],
  instagram: ["instagram"],
  x: ["x"],
  website: ["website"],
  rateThisCompany: [
    "rateThisCompany",
    "actualData",
    "rate",
    "rating",
    "h3",
    "comment",
    "confirmRate",
    "button2",
    "companyRated",
    "rateSum2",
    "customerRated",
    "rateSum3"
  ],
  actualData: ["actualData"],
  rate: ["rate", "rating", "h3", "comment", "confirmRate", "button2"],
  rating: ["rating"],
  h3: ["h3"],
  comment: ["comment"],
  confirmRate: ["confirmRate"],
  button2: ["button2"],
  companyRated: ["companyRated"],
  rateSum2: ["rateSum2"],
  customerRated: ["customerRated"],
  rateSum3: ["rateSum3"],
  reportRate: [
    "reportRate",
    "reportData",
    "companyRate",
    "customerInstruction",
    "averageRatingReceived"
  ],
  reportData: ["reportData"],
  companyRate: ["companyRate"],
  customerInstruction: ["customerInstruction"],
  averageRatingReceived: ["averageRatingReceived"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  topBar: "div";
  navigationBar: typeof NavigationBar;
  account: typeof AntdDropdown;
  button: typeof AntdButton;
  countainer1: "div";
  companyLogo: typeof PlasmicImg__;
  companyName: "div";
  companyType: "div";
  averageRate: typeof AntdRate;
  rateSum: "div";
  area: "div";
  subArea: "div";
  location: "div";
  foundationDate: "div";
  goalsSum: "div";
  partnershipLink: typeof LoginButton;
  companyTagline: "div";
  linkedIn: "a";
  instagram: "a";
  x: "a";
  website: "a";
  rateThisCompany: "div";
  actualData: "div";
  rate: typeof Modal;
  rating: typeof AntdRate;
  h3: "h3";
  comment: typeof AntdTextArea;
  confirmRate: typeof Button2;
  button2: typeof Button2;
  companyRated: typeof AntdRate;
  rateSum2: "div";
  customerRated: typeof AntdRate;
  rateSum3: "div";
  reportRate: "div";
  reportData: "div";
  companyRate: typeof AntdRate;
  customerInstruction: typeof AntdRate;
  averageRatingReceived: typeof AntdRate;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicARatingCompanies__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicARatingCompanies__VariantsArgs;
    args?: PlasmicARatingCompanies__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicARatingCompanies__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicARatingCompanies__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicARatingCompanies__ArgProps,
          internalVariantPropNames: PlasmicARatingCompanies__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicARatingCompanies__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicARatingCompanies";
  } else {
    func.displayName = `PlasmicARatingCompanies.${nodeName}`;
  }
  return func;
}

export const PlasmicARatingCompanies = Object.assign(
  // Top-level PlasmicARatingCompanies renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    topBar: makeNodeComponent("topBar"),
    navigationBar: makeNodeComponent("navigationBar"),
    account: makeNodeComponent("account"),
    button: makeNodeComponent("button"),
    countainer1: makeNodeComponent("countainer1"),
    companyLogo: makeNodeComponent("companyLogo"),
    companyName: makeNodeComponent("companyName"),
    companyType: makeNodeComponent("companyType"),
    averageRate: makeNodeComponent("averageRate"),
    rateSum: makeNodeComponent("rateSum"),
    area: makeNodeComponent("area"),
    subArea: makeNodeComponent("subArea"),
    location: makeNodeComponent("location"),
    foundationDate: makeNodeComponent("foundationDate"),
    goalsSum: makeNodeComponent("goalsSum"),
    partnershipLink: makeNodeComponent("partnershipLink"),
    companyTagline: makeNodeComponent("companyTagline"),
    linkedIn: makeNodeComponent("linkedIn"),
    instagram: makeNodeComponent("instagram"),
    x: makeNodeComponent("x"),
    website: makeNodeComponent("website"),
    rateThisCompany: makeNodeComponent("rateThisCompany"),
    actualData: makeNodeComponent("actualData"),
    rate: makeNodeComponent("rate"),
    rating: makeNodeComponent("rating"),
    h3: makeNodeComponent("h3"),
    comment: makeNodeComponent("comment"),
    confirmRate: makeNodeComponent("confirmRate"),
    button2: makeNodeComponent("button2"),
    companyRated: makeNodeComponent("companyRated"),
    rateSum2: makeNodeComponent("rateSum2"),
    customerRated: makeNodeComponent("customerRated"),
    rateSum3: makeNodeComponent("rateSum3"),
    reportRate: makeNodeComponent("reportRate"),
    reportData: makeNodeComponent("reportData"),
    companyRate: makeNodeComponent("companyRate"),
    customerInstruction: makeNodeComponent("customerInstruction"),
    averageRatingReceived: makeNodeComponent("averageRatingReceived"),

    // Metadata about props expected for PlasmicARatingCompanies
    internalVariantProps: PlasmicARatingCompanies__VariantProps,
    internalArgProps: PlasmicARatingCompanies__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/a-rating-companies",
      pagePath: "/a-rating-companies",
      params: {},
      query: {}
    })
  }
);

export default PlasmicARatingCompanies;
/* prettier-ignore-end */
