/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5uU4LbmmcY9V8oBke7M62e
// Component: Rw7ihVwxSCxA

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { AntdTextArea } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdTextArea_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import Modal from "../../Modal"; // plasmic-import: 2mIwXeE-_Psc/component
import LoginButton from "../../LoginButton"; // plasmic-import: DYHdsjcJLpSq/component
import { AntdDatePicker } from "@plasmicpkgs/antd5/skinny/registerDatePicker";
import { datePickerHelpers as AntdDatePicker_Helpers } from "@plasmicpkgs/antd5/skinny/registerDatePicker";
import Button2 from "../../Button2"; // plasmic-import: t1SFzVEz5RlV/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 5uU4LbmmcY9V8oBke7M62e/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 5uU4LbmmcY9V8oBke7M62e/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 5uU4LbmmcY9V8oBke7M62e/projectcss
import sty from "./PlasmicUTableAtCompanyLocation.module.css"; // plasmic-import: Rw7ihVwxSCxA/css

import _14655891761535698998SvgIcon from "./icons/PlasmicIcon___14655891761535698998Svg"; // plasmic-import: rgtq7QH0uFjW/icon
import UserSvgIcon from "./icons/PlasmicIcon__UserSvg"; // plasmic-import: vF6c8HVR1OWZ/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: 2MH9wfBMgppQ/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: _eklczUQ9Bdt/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: l4RREmL1A-vM/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: qJDdQLGS2RlC/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "Confirm order",

    openGraph: {
      title: "Confirm order"
    },
    twitter: {
      card: "summary",
      title: "Confirm order"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicUTableAtCompanyLocation__VariantMembers = {};
export type PlasmicUTableAtCompanyLocation__VariantsArgs = {};
type VariantPropType = keyof PlasmicUTableAtCompanyLocation__VariantsArgs;
export const PlasmicUTableAtCompanyLocation__VariantProps =
  new Array<VariantPropType>();

export type PlasmicUTableAtCompanyLocation__ArgsType = {
  eMailInput2?: React.ReactNode;
};
type ArgPropType = keyof PlasmicUTableAtCompanyLocation__ArgsType;
export const PlasmicUTableAtCompanyLocation__ArgProps = new Array<ArgPropType>(
  "eMailInput2"
);

export type PlasmicUTableAtCompanyLocation__OverridesType = {
  root?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  rectangle?: Flex__<"div">;
  solution?: Flex__<"div">;
  textArea?: Flex__<typeof AntdTextArea>;
  comeToAddress?: Flex__<"div">;
  schedule?: Flex__<typeof Modal>;
  timePicker?: Flex__<typeof AntdDatePicker>;
  _continue?: Flex__<typeof Modal>;
  addCard?: Flex__<typeof Modal>;
  reviewRequest?: Flex__<typeof Modal>;
  getInTheWaitingLine?: Flex__<typeof Modal>;
  addCard2?: Flex__<typeof Modal>;
  reviewRequest2?: Flex__<typeof Modal>;
};

export interface DefaultUTableAtCompanyLocationProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicUTableAtCompanyLocation__RenderFunc(props: {
  variants: PlasmicUTableAtCompanyLocation__VariantsArgs;
  args: PlasmicUTableAtCompanyLocation__ArgsType;
  overrides: PlasmicUTableAtCompanyLocation__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "textArea.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdTextArea_Helpers)
      },
      {
        path: "_continue.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "addCard.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "reviewRequest.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "getInTheWaitingLine.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "addCard2.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "reviewRequest2.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "schedule.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "timePicker.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdDatePicker_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <PlasmicImg__
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={"100px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"auto"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "400px"
                : "700px"
            }
            loading={"lazy"}
            src={{
              src: "/plasmic/ez_marketing_platform_sacanagem/images/logo2Svg.svg",
              fullWidth: 297,
              fullHeight: 210,
              aspectRatio: undefined
            }}
          />

          <div
            data-plasmic-name={"rectangle"}
            data-plasmic-override={overrides.rectangle}
            className={classNames(projectcss.all, sty.rectangle)}
          >
            <div
              data-plasmic-name={"solution"}
              data-plasmic-override={overrides.solution}
              className={classNames(projectcss.all, sty.solution)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___65QS
                )}
              >
                {"Solution"}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__i55B8)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lo0Bz
                  )}
                >
                  {
                    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy "
                  }
                </div>
                <div className={classNames(projectcss.all, sty.freeBox___0Php)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gvg9Y
                    )}
                  >
                    {"[step]"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hIn88
                    )}
                  >
                    {"[step]"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sJgry
                    )}
                  >
                    {"[step]"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vCpOo
                    )}
                  >
                    {"[step]"}
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__kLXuT)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3Iyic
                  )}
                >
                  {"U$"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rk2Uh
                  )}
                >
                  {"700,00"}
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dulsW
                )}
              >
                {"Any comments?"}
              </div>
              {(() => {
                const child$Props = {
                  bordered: true,
                  className: classNames("__wab_instance", sty.textArea),
                  onChange: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "value",
                      ["textArea", "value"],
                      AntdTextArea_Helpers
                    ).apply(null, eventArgs);
                  },
                  value: generateStateValueProp($state, ["textArea", "value"])
                };
                initializeCodeComponentStates(
                  $state,
                  [
                    {
                      name: "value",
                      plasmicStateName: "textArea.value"
                    }
                  ],
                  [],
                  AntdTextArea_Helpers ?? {},
                  child$Props
                );

                return (
                  <AntdTextArea
                    data-plasmic-name={"textArea"}
                    data-plasmic-override={overrides.textArea}
                    {...child$Props}
                  />
                );
              })()}
            </div>
            <div
              data-plasmic-name={"comeToAddress"}
              data-plasmic-override={overrides.comeToAddress}
              className={classNames(projectcss.all, sty.comeToAddress)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___6A1Df
                )}
              >
                {"Come to address"}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__hhXxg)}>
                <_14655891761535698998SvgIcon
                  className={classNames(projectcss.all, sty.svg__iGjdi)}
                  role={"img"}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox___5P2Av)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oeZGd
                    )}
                  >
                    {"R. Uruguai, 244"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uc0Ue
                    )}
                  >
                    {"Jadim Alvorada"}
                  </div>
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__vbVpK)}>
              <UserSvgIcon
                className={classNames(projectcss.all, sty.svg__lxtnb)}
                role={"img"}
              />

              {renderPlasmicSlot({
                defaultContents: (() => {
                  const child$Props = {
                    autoFocus: false,
                    bordered: true,
                    className: classNames("__wab_instance", sty.input__q561Y),
                    placeholder: "Email",
                    readOnly: false,
                    size: "middle",
                    type: "email"
                  };

                  return <AntdInput {...child$Props} />;
                })(),
                value: args.eMailInput2,
                className: classNames(sty.slotTargetEMailInput2)
              })}
            </div>
            <Modal
              data-plasmic-name={"schedule"}
              data-plasmic-override={overrides.schedule}
              className={classNames("__wab_instance", sty.schedule)}
              closeOnBackdropClick={false}
              content={
                <div className={classNames(projectcss.all, sty.freeBox__llHKk)}>
                  {(() => {
                    const child$Props = {
                      className: classNames("__wab_instance", sty.timePicker),
                      onChange: async (...eventArgs: any) => {
                        generateStateOnChangePropForCodeComponents(
                          $state,
                          "value",
                          ["timePicker", "value"],
                          AntdDatePicker_Helpers
                        ).apply(null, eventArgs);
                      },
                      popupScopeClassName: sty["timePicker__datePickerPopup"],
                      value: generateStateValueProp($state, [
                        "timePicker",
                        "value"
                      ])
                    };
                    initializeCodeComponentStates(
                      $state,
                      [
                        {
                          name: "value",
                          plasmicStateName: "timePicker.value"
                        }
                      ],
                      [],
                      AntdDatePicker_Helpers ?? {},
                      child$Props
                    );

                    return (
                      <AntdDatePicker
                        data-plasmic-name={"timePicker"}
                        data-plasmic-override={overrides.timePicker}
                        {...child$Props}
                      />
                    );
                  })()}
                </div>
              }
              footer={
                <div className={classNames(projectcss.all, sty.freeBox__fXrA3)}>
                  <Button2
                    color={"muted"}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zuu3I
                        )}
                      >
                        {"Close"}
                      </div>
                    }
                    onClick={async event => {
                      const $steps = {};

                      $steps["updateModal2IsOpen"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["schedule", "isOpen"]
                              },
                              operation: 0,
                              value: false
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateModal2IsOpen"] != null &&
                        typeof $steps["updateModal2IsOpen"] === "object" &&
                        typeof $steps["updateModal2IsOpen"].then === "function"
                      ) {
                        $steps["updateModal2IsOpen"] =
                          await $steps["updateModal2IsOpen"];
                      }
                    }}
                    type={"soft"}
                  />

                  <Modal
                    data-plasmic-name={"_continue"}
                    data-plasmic-override={overrides._continue}
                    className={classNames("__wab_instance", sty._continue)}
                    content={
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___7N22U
                        )}
                      >
                        <Modal
                          data-plasmic-name={"addCard"}
                          data-plasmic-override={overrides.addCard}
                          className={classNames("__wab_instance", sty.addCard)}
                          content={
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__ff8AB
                              )}
                            />
                          }
                          footer={
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__y3B4L
                              )}
                            >
                              <Button2
                                color={"muted"}
                                label={
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__rlWXa
                                    )}
                                  >
                                    {"Close"}
                                  </div>
                                }
                                onClick={async event => {
                                  const $steps = {};

                                  $steps["updateModal2IsOpen"] = true
                                    ? (() => {
                                        const actionArgs = {
                                          variable: {
                                            objRoot: $state,
                                            variablePath: ["addCard", "isOpen"]
                                          },
                                          operation: 0,
                                          value: false
                                        };
                                        return (({
                                          variable,
                                          value,
                                          startIndex,
                                          deleteCount
                                        }) => {
                                          if (!variable) {
                                            return;
                                          }
                                          const { objRoot, variablePath } =
                                            variable;

                                          $stateSet(
                                            objRoot,
                                            variablePath,
                                            value
                                          );
                                          return value;
                                        })?.apply(null, [actionArgs]);
                                      })()
                                    : undefined;
                                  if (
                                    $steps["updateModal2IsOpen"] != null &&
                                    typeof $steps["updateModal2IsOpen"] ===
                                      "object" &&
                                    typeof $steps["updateModal2IsOpen"].then ===
                                      "function"
                                  ) {
                                    $steps["updateModal2IsOpen"] =
                                      await $steps["updateModal2IsOpen"];
                                  }
                                }}
                                type={"soft"}
                              />
                            </div>
                          }
                          heading={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__iuydh
                              )}
                            >
                              {"Holding the payment"}
                            </h3>
                          }
                          isOpen={generateStateValueProp($state, [
                            "addCard",
                            "isOpen"
                          ])}
                          onOpenChange={async (...eventArgs: any) => {
                            generateStateOnChangeProp($state, [
                              "addCard",
                              "isOpen"
                            ]).apply(null, eventArgs);

                            if (
                              eventArgs.length > 1 &&
                              eventArgs[1] &&
                              eventArgs[1]._plasmic_state_init_
                            ) {
                              return;
                            }
                          }}
                          trigger={
                            <LoginButton
                              className={classNames(
                                "__wab_instance",
                                sty.loginButton__naLvh
                              )}
                              color={"white"}
                              onClick={async event => {
                                const $steps = {};
                              }}
                              shape={"rounded"}
                              size={"compact"}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__vaRJ
                                )}
                              >
                                {"Add card"}
                              </div>
                            </LoginButton>
                          }
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fK8Sq
                          )}
                        >
                          {"Solution"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__eznrc
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__uuNjR
                            )}
                          >
                            {"U$"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__knm52
                            )}
                          >
                            {"700,00"}
                          </div>
                        </div>
                      </div>
                    }
                    footer={
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__v6Raq
                        )}
                      >
                        <Modal
                          data-plasmic-name={"reviewRequest"}
                          data-plasmic-override={overrides.reviewRequest}
                          className={classNames(
                            "__wab_instance",
                            sty.reviewRequest
                          )}
                          content={
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__kwdVq
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__scV0
                                )}
                              >
                                <_14655891761535698998SvgIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__wqPbh
                                  )}
                                  role={"img"}
                                />

                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__aEveR
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__h2X0
                                    )}
                                  >
                                    {"R. Uruguai, 244"}
                                  </div>
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__rTsxL
                                    )}
                                  >
                                    {"Jadim Alvorada"}
                                  </div>
                                </div>
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___2KqWw
                                )}
                              >
                                {"Solution"}
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__x4X1P
                                )}
                              >
                                {
                                  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy "
                                }
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox___8Acfw
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__ydYkK
                                  )}
                                >
                                  {"U$"}
                                </div>
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__lZvJg
                                  )}
                                >
                                  {"700,00"}
                                </div>
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__iFdSa
                                )}
                              >
                                {"carlos_galindo@hotmail.com"}
                              </div>
                            </div>
                          }
                          footer={
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__qLXfw
                              )}
                            >
                              <Button2
                                color={"muted"}
                                label={
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__otGa3
                                    )}
                                  >
                                    {"Cancel"}
                                  </div>
                                }
                                onClick={async event => {
                                  const $steps = {};

                                  $steps["updateModalIsOpen"] = true
                                    ? (() => {
                                        const actionArgs = {
                                          variable: {
                                            objRoot: $state,
                                            variablePath: [
                                              "reviewRequest",
                                              "isOpen"
                                            ]
                                          },
                                          operation: 0,
                                          value: false
                                        };
                                        return (({
                                          variable,
                                          value,
                                          startIndex,
                                          deleteCount
                                        }) => {
                                          if (!variable) {
                                            return;
                                          }
                                          const { objRoot, variablePath } =
                                            variable;

                                          $stateSet(
                                            objRoot,
                                            variablePath,
                                            value
                                          );
                                          return value;
                                        })?.apply(null, [actionArgs]);
                                      })()
                                    : undefined;
                                  if (
                                    $steps["updateModalIsOpen"] != null &&
                                    typeof $steps["updateModalIsOpen"] ===
                                      "object" &&
                                    typeof $steps["updateModalIsOpen"].then ===
                                      "function"
                                  ) {
                                    $steps["updateModalIsOpen"] =
                                      await $steps["updateModalIsOpen"];
                                  }
                                }}
                                type={"soft"}
                              />

                              <LoginButton
                                className={classNames(
                                  "__wab_instance",
                                  sty.loginButton__kgqxa
                                )}
                                onClick={async event => {
                                  const $steps = {};

                                  $steps[
                                    "goToUTableAtCompanyLocationConfirmService"
                                  ] = true
                                    ? (() => {
                                        const actionArgs = {
                                          destination: `/u-table-at-company-location-confirm`
                                        };
                                        return (({ destination }) => {
                                          if (
                                            typeof destination === "string" &&
                                            destination.startsWith("#")
                                          ) {
                                            document
                                              .getElementById(
                                                destination.substr(1)
                                              )
                                              .scrollIntoView({
                                                behavior: "smooth"
                                              });
                                          } else {
                                            __nextRouter?.push(destination);
                                          }
                                        })?.apply(null, [actionArgs]);
                                      })()
                                    : undefined;
                                  if (
                                    $steps[
                                      "goToUTableAtCompanyLocationConfirmService"
                                    ] != null &&
                                    typeof $steps[
                                      "goToUTableAtCompanyLocationConfirmService"
                                    ] === "object" &&
                                    typeof $steps[
                                      "goToUTableAtCompanyLocationConfirmService"
                                    ].then === "function"
                                  ) {
                                    $steps[
                                      "goToUTableAtCompanyLocationConfirmService"
                                    ] =
                                      await $steps[
                                        "goToUTableAtCompanyLocationConfirmService"
                                      ];
                                  }
                                }}
                                size={"compact"}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__bw0J9
                                  )}
                                >
                                  {"Confirm"}
                                </div>
                              </LoginButton>
                            </div>
                          }
                          heading={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__udK18
                              )}
                            >
                              {"06/11/2025 - 5:04 PM"}
                            </h3>
                          }
                          isOpen={generateStateValueProp($state, [
                            "reviewRequest",
                            "isOpen"
                          ])}
                          onOpenChange={async (...eventArgs: any) => {
                            generateStateOnChangeProp($state, [
                              "reviewRequest",
                              "isOpen"
                            ]).apply(null, eventArgs);

                            if (
                              eventArgs.length > 1 &&
                              eventArgs[1] &&
                              eventArgs[1]._plasmic_state_init_
                            ) {
                              return;
                            }
                          }}
                          trigger={
                            <LoginButton
                              className={classNames(
                                "__wab_instance",
                                sty.loginButton___5RzKa
                              )}
                              size={"compact"}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__jecd
                                )}
                              >
                                {"Review request"}
                              </div>
                            </LoginButton>
                          }
                        />

                        <Button2
                          color={"muted"}
                          label={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__jErUq
                              )}
                            >
                              {"Close"}
                            </div>
                          }
                          onClick={async event => {
                            const $steps = {};

                            $steps["updateModal2IsOpen"] = true
                              ? (() => {
                                  const actionArgs = {
                                    variable: {
                                      objRoot: $state,
                                      variablePath: ["_continue", "isOpen"]
                                    },
                                    operation: 0,
                                    value: false
                                  };
                                  return (({
                                    variable,
                                    value,
                                    startIndex,
                                    deleteCount
                                  }) => {
                                    if (!variable) {
                                      return;
                                    }
                                    const { objRoot, variablePath } = variable;

                                    $stateSet(objRoot, variablePath, value);
                                    return value;
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                            if (
                              $steps["updateModal2IsOpen"] != null &&
                              typeof $steps["updateModal2IsOpen"] ===
                                "object" &&
                              typeof $steps["updateModal2IsOpen"].then ===
                                "function"
                            ) {
                              $steps["updateModal2IsOpen"] =
                                await $steps["updateModal2IsOpen"];
                            }
                          }}
                          type={"soft"}
                        />
                      </div>
                    }
                    heading={
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__mF64F
                        )}
                      >
                        {"Holding the payment"}
                      </h3>
                    }
                    isOpen={generateStateValueProp($state, [
                      "_continue",
                      "isOpen"
                    ])}
                    onOpenChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "_continue",
                        "isOpen"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                    trigger={
                      <LoginButton
                        className={classNames(
                          "__wab_instance",
                          sty.loginButton__urqSn
                        )}
                        onClick={async event => {
                          const $steps = {};
                        }}
                        size={"compact"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__yxvki
                          )}
                        >
                          {"Continue"}
                        </div>
                      </LoginButton>
                    }
                  />
                </div>
              }
              heading={
                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__nBYd
                  )}
                >
                  {"Schedule a time"}
                </h3>
              }
              isOpen={generateStateValueProp($state, ["schedule", "isOpen"])}
              onOpenChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, ["schedule", "isOpen"]).apply(
                  null,
                  eventArgs
                );

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              trigger={
                <LoginButton
                  className={classNames(
                    "__wab_instance",
                    sty.loginButton__bxTcC
                  )}
                  onClick={async event => {
                    const $steps = {};
                  }}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1IdPi
                    )}
                  >
                    {"Schedule"}
                  </div>
                </LoginButton>
              }
            />

            <Modal
              data-plasmic-name={"getInTheWaitingLine"}
              data-plasmic-override={overrides.getInTheWaitingLine}
              className={classNames("__wab_instance", sty.getInTheWaitingLine)}
              content={
                <div className={classNames(projectcss.all, sty.freeBox__zgmX1)}>
                  <Modal
                    data-plasmic-name={"addCard2"}
                    data-plasmic-override={overrides.addCard2}
                    className={classNames("__wab_instance", sty.addCard2)}
                    content={
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__gNPlM
                        )}
                      />
                    }
                    footer={
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__dDpgo
                        )}
                      >
                        <Button2
                          color={"muted"}
                          label={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__nh6Mw
                              )}
                            >
                              {"Close"}
                            </div>
                          }
                          onClick={async event => {
                            const $steps = {};

                            $steps["updateModal2IsOpen"] = true
                              ? (() => {
                                  const actionArgs = {
                                    variable: {
                                      objRoot: $state,
                                      variablePath: ["addCard2", "isOpen"]
                                    },
                                    operation: 0,
                                    value: false
                                  };
                                  return (({
                                    variable,
                                    value,
                                    startIndex,
                                    deleteCount
                                  }) => {
                                    if (!variable) {
                                      return;
                                    }
                                    const { objRoot, variablePath } = variable;

                                    $stateSet(objRoot, variablePath, value);
                                    return value;
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                            if (
                              $steps["updateModal2IsOpen"] != null &&
                              typeof $steps["updateModal2IsOpen"] ===
                                "object" &&
                              typeof $steps["updateModal2IsOpen"].then ===
                                "function"
                            ) {
                              $steps["updateModal2IsOpen"] =
                                await $steps["updateModal2IsOpen"];
                            }
                          }}
                          type={"soft"}
                        />
                      </div>
                    }
                    heading={
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__x9VH
                        )}
                      >
                        {"Holding the payment"}
                      </h3>
                    }
                    isOpen={generateStateValueProp($state, [
                      "addCard2",
                      "isOpen"
                    ])}
                    onOpenChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "addCard2",
                        "isOpen"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                    trigger={
                      <LoginButton
                        className={classNames(
                          "__wab_instance",
                          sty.loginButton__oyu5D
                        )}
                        color={"white"}
                        onClick={async event => {
                          const $steps = {};
                        }}
                        shape={"rounded"}
                        size={"compact"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__jzDjQ
                          )}
                        >
                          {"Add card"}
                        </div>
                      </LoginButton>
                    }
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__liGhz
                    )}
                  >
                    {"Solution"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__jEcau)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jkzof
                      )}
                    >
                      {"U$"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__u31
                      )}
                    >
                      {"700,00"}
                    </div>
                  </div>
                </div>
              }
              footer={
                <div className={classNames(projectcss.all, sty.freeBox__jkt3)}>
                  <Modal
                    data-plasmic-name={"reviewRequest2"}
                    data-plasmic-override={overrides.reviewRequest2}
                    className={classNames("__wab_instance", sty.reviewRequest2)}
                    content={
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__u9Pxi
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___1E1Gs
                          )}
                        >
                          <_14655891761535698998SvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__mdxvV
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__j9BwP
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__bzl72
                              )}
                            >
                              {"R. Uruguai, 244"}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__f6Lrk
                              )}
                            >
                              {"Jadim Alvorada"}
                            </div>
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__nFtIx
                          )}
                        >
                          {"Solution"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___9T5L2
                          )}
                        >
                          {
                            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy "
                          }
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__tn44X
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__pv7N
                            )}
                          >
                            {"U$"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__c33Ee
                            )}
                          >
                            {"700,00"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__yq2S7
                          )}
                        >
                          {"carlos_galindo@hotmail.com"}
                        </div>
                      </div>
                    }
                    footer={
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__lOoej
                        )}
                      >
                        <Button2
                          color={"muted"}
                          label={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__sYtnW
                              )}
                            >
                              {"Cancel"}
                            </div>
                          }
                          onClick={async event => {
                            const $steps = {};

                            $steps["updateModalIsOpen"] = true
                              ? (() => {
                                  const actionArgs = {
                                    variable: {
                                      objRoot: $state,
                                      variablePath: ["reviewRequest2", "isOpen"]
                                    },
                                    operation: 0,
                                    value: false
                                  };
                                  return (({
                                    variable,
                                    value,
                                    startIndex,
                                    deleteCount
                                  }) => {
                                    if (!variable) {
                                      return;
                                    }
                                    const { objRoot, variablePath } = variable;

                                    $stateSet(objRoot, variablePath, value);
                                    return value;
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                            if (
                              $steps["updateModalIsOpen"] != null &&
                              typeof $steps["updateModalIsOpen"] === "object" &&
                              typeof $steps["updateModalIsOpen"].then ===
                                "function"
                            ) {
                              $steps["updateModalIsOpen"] =
                                await $steps["updateModalIsOpen"];
                            }
                          }}
                          type={"soft"}
                        />

                        <LoginButton
                          className={classNames(
                            "__wab_instance",
                            sty.loginButton__saEmN
                          )}
                          onClick={async event => {
                            const $steps = {};

                            $steps[
                              "goToUTableAtCompanyLocationConfirmService"
                            ] = true
                              ? (() => {
                                  const actionArgs = {
                                    destination: `/u-table-at-company-location-confirm`
                                  };
                                  return (({ destination }) => {
                                    if (
                                      typeof destination === "string" &&
                                      destination.startsWith("#")
                                    ) {
                                      document
                                        .getElementById(destination.substr(1))
                                        .scrollIntoView({ behavior: "smooth" });
                                    } else {
                                      __nextRouter?.push(destination);
                                    }
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                            if (
                              $steps[
                                "goToUTableAtCompanyLocationConfirmService"
                              ] != null &&
                              typeof $steps[
                                "goToUTableAtCompanyLocationConfirmService"
                              ] === "object" &&
                              typeof $steps[
                                "goToUTableAtCompanyLocationConfirmService"
                              ].then === "function"
                            ) {
                              $steps[
                                "goToUTableAtCompanyLocationConfirmService"
                              ] =
                                await $steps[
                                  "goToUTableAtCompanyLocationConfirmService"
                                ];
                            }
                          }}
                          size={"compact"}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gsTh7
                            )}
                          >
                            {"Confirm"}
                          </div>
                        </LoginButton>
                      </div>
                    }
                    heading={null}
                    isOpen={generateStateValueProp($state, [
                      "reviewRequest2",
                      "isOpen"
                    ])}
                    onOpenChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "reviewRequest2",
                        "isOpen"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                    trigger={
                      <LoginButton
                        className={classNames(
                          "__wab_instance",
                          sty.loginButton__jl371
                        )}
                        size={"compact"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__cymKq
                          )}
                        >
                          {"Review request"}
                        </div>
                      </LoginButton>
                    }
                  />

                  <Button2
                    color={"muted"}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tS0Mj
                        )}
                      >
                        {"Close"}
                      </div>
                    }
                    onClick={async event => {
                      const $steps = {};

                      $steps["updateModal2IsOpen"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["getInTheWaitingLine", "isOpen"]
                              },
                              operation: 0,
                              value: false
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateModal2IsOpen"] != null &&
                        typeof $steps["updateModal2IsOpen"] === "object" &&
                        typeof $steps["updateModal2IsOpen"].then === "function"
                      ) {
                        $steps["updateModal2IsOpen"] =
                          await $steps["updateModal2IsOpen"];
                      }
                    }}
                    type={"soft"}
                  />
                </div>
              }
              heading={
                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__eka3Y
                  )}
                >
                  {"Holding the payment"}
                </h3>
              }
              isOpen={generateStateValueProp($state, [
                "getInTheWaitingLine",
                "isOpen"
              ])}
              onOpenChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "getInTheWaitingLine",
                  "isOpen"
                ]).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              trigger={
                <LoginButton
                  className={classNames(
                    "__wab_instance",
                    sty.loginButton___6QLel
                  )}
                  onClick={async event => {
                    const $steps = {};
                  }}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zXAo
                    )}
                  >
                    {"Get in the waiting line"}
                  </div>
                </LoginButton>
              }
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "img",
    "rectangle",
    "solution",
    "textArea",
    "comeToAddress",
    "schedule",
    "timePicker",
    "_continue",
    "addCard",
    "reviewRequest",
    "getInTheWaitingLine",
    "addCard2",
    "reviewRequest2"
  ],
  img: ["img"],
  rectangle: [
    "rectangle",
    "solution",
    "textArea",
    "comeToAddress",
    "schedule",
    "timePicker",
    "_continue",
    "addCard",
    "reviewRequest",
    "getInTheWaitingLine",
    "addCard2",
    "reviewRequest2"
  ],
  solution: ["solution", "textArea"],
  textArea: ["textArea"],
  comeToAddress: ["comeToAddress"],
  schedule: ["schedule", "timePicker", "_continue", "addCard", "reviewRequest"],
  timePicker: ["timePicker"],
  _continue: ["_continue", "addCard", "reviewRequest"],
  addCard: ["addCard"],
  reviewRequest: ["reviewRequest"],
  getInTheWaitingLine: ["getInTheWaitingLine", "addCard2", "reviewRequest2"],
  addCard2: ["addCard2"],
  reviewRequest2: ["reviewRequest2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof PlasmicImg__;
  rectangle: "div";
  solution: "div";
  textArea: typeof AntdTextArea;
  comeToAddress: "div";
  schedule: typeof Modal;
  timePicker: typeof AntdDatePicker;
  _continue: typeof Modal;
  addCard: typeof Modal;
  reviewRequest: typeof Modal;
  getInTheWaitingLine: typeof Modal;
  addCard2: typeof Modal;
  reviewRequest2: typeof Modal;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicUTableAtCompanyLocation__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicUTableAtCompanyLocation__VariantsArgs;
    args?: PlasmicUTableAtCompanyLocation__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicUTableAtCompanyLocation__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicUTableAtCompanyLocation__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicUTableAtCompanyLocation__ArgProps,
          internalVariantPropNames: PlasmicUTableAtCompanyLocation__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicUTableAtCompanyLocation__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicUTableAtCompanyLocation";
  } else {
    func.displayName = `PlasmicUTableAtCompanyLocation.${nodeName}`;
  }
  return func;
}

export const PlasmicUTableAtCompanyLocation = Object.assign(
  // Top-level PlasmicUTableAtCompanyLocation renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    rectangle: makeNodeComponent("rectangle"),
    solution: makeNodeComponent("solution"),
    textArea: makeNodeComponent("textArea"),
    comeToAddress: makeNodeComponent("comeToAddress"),
    schedule: makeNodeComponent("schedule"),
    timePicker: makeNodeComponent("timePicker"),
    _continue: makeNodeComponent("_continue"),
    addCard: makeNodeComponent("addCard"),
    reviewRequest: makeNodeComponent("reviewRequest"),
    getInTheWaitingLine: makeNodeComponent("getInTheWaitingLine"),
    addCard2: makeNodeComponent("addCard2"),
    reviewRequest2: makeNodeComponent("reviewRequest2"),

    // Metadata about props expected for PlasmicUTableAtCompanyLocation
    internalVariantProps: PlasmicUTableAtCompanyLocation__VariantProps,
    internalArgProps: PlasmicUTableAtCompanyLocation__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/u-table-at-company-location",
      pagePath: "/u-table-at-company-location",
      params: {},
      query: {}
    })
  }
);

export default PlasmicUTableAtCompanyLocation;
/* prettier-ignore-end */
