/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5uU4LbmmcY9V8oBke7M62e
// Component: ZACVx7ys8B-l

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import LoginButton from "../../LoginButton"; // plasmic-import: DYHdsjcJLpSq/component
import ListingListBox from "../../ListingListBox"; // plasmic-import: TtM6MATgCvVt/component
import Button4 from "../../Button4"; // plasmic-import: QBrQpOnv-BA6/component
import FooterSection from "../../FooterSection"; // plasmic-import: u6frPd1Kf3_M/component
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 5uU4LbmmcY9V8oBke7M62e/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 5uU4LbmmcY9V8oBke7M62e/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 5uU4LbmmcY9V8oBke7M62e/projectcss
import sty from "./PlasmicCLandingPage.module.css"; // plasmic-import: ZACVx7ys8B-l/css

import Icon13Icon from "./icons/PlasmicIcon__Icon13"; // plasmic-import: syymrE_8WT-Y/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: 2MH9wfBMgppQ/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: _eklczUQ9Bdt/icon
import ChevronDown2Icon from "./icons/PlasmicIcon__ChevronDown2"; // plasmic-import: sPEUruxni1ML/icon
import _47SvgIcon from "./icons/PlasmicIcon___47Svg"; // plasmic-import: PZR08tvoBSBZ/icon
import _62SvgIcon from "./icons/PlasmicIcon___62Svg"; // plasmic-import: NE1EzB_qCnEf/icon
import _74SvgIcon from "./icons/PlasmicIcon___74Svg"; // plasmic-import: sacHv-0fGeA_/icon
import MoneySvgrepoComSvgIcon from "./icons/PlasmicIcon__MoneySvgrepoComSvg"; // plasmic-import: Dc-OAwyNJ6-Y/icon
import TrophySportsAndCompetitionSvgrepoComSvgIcon from "./icons/PlasmicIcon__TrophySportsAndCompetitionSvgrepoComSvg"; // plasmic-import: -NiJtbFUHgnf/icon
import ReportSvgrepoComSvgIcon from "./icons/PlasmicIcon__ReportSvgrepoComSvg"; // plasmic-import: gD88w6PLGoom/icon
import Icon15Icon from "./icons/PlasmicIcon__Icon15"; // plasmic-import: Ak65bnuouuJJ/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: l4RREmL1A-vM/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "Corporation landing page",

    openGraph: {
      title: "Corporation landing page"
    },
    twitter: {
      card: "summary" as const,
      title: "Corporation landing page"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicCLandingPage__VariantMembers = {};
export type PlasmicCLandingPage__VariantsArgs = {};
type VariantPropType = keyof PlasmicCLandingPage__VariantsArgs;
export const PlasmicCLandingPage__VariantProps = new Array<VariantPropType>();

export type PlasmicCLandingPage__ArgsType = {};
type ArgPropType = keyof PlasmicCLandingPage__ArgsType;
export const PlasmicCLandingPage__ArgProps = new Array<ArgPropType>();

export type PlasmicCLandingPage__OverridesType = {
  root?: Flex__<"div">;
  cabecalho?: Flex__<"div">;
  h1?: Flex__<"h1">;
  subtituloEProblema?: Flex__<"div">;
  subtitulo?: Flex__<"div">;
  problem2?: Flex__<"div">;
  title?: Flex__<"div">;
  h3?: Flex__<"h3">;
  solucao?: Flex__<"div">;
  foreground2?: Flex__<"div">;
  vantagens?: Flex__<"div">;
  provaSocial?: Flex__<"div">;
  left2?: Flex__<"div">;
  button4?: Flex__<typeof Button4>;
  footerSection?: Flex__<typeof FooterSection>;
  metaPixel?: Flex__<typeof Embed>;
};

export interface DefaultCLandingPageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCLandingPage__RenderFunc(props: {
  variants: PlasmicCLandingPage__VariantsArgs;
  args: PlasmicCLandingPage__ArgsType;
  overrides: PlasmicCLandingPage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"cabecalho"}
            data-plasmic-override={overrides.cabecalho}
            className={classNames(projectcss.all, sty.cabecalho)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__fJ3)}>
              <div className={classNames(projectcss.all, sty.freeBox__ix2Kf)}>
                <div className={classNames(projectcss.all, sty.freeBox__poBdt)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__cQrGr)}
                    displayHeight={"100px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "300px"
                        : "500px"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/ez_marketing_platform_sacanagem/images/logoPng3.png",
                      fullWidth: 2888,
                      fullHeight: 392,
                      aspectRatio: undefined
                    }}
                  />

                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.h1__5uU4L,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"COMPANIES: GROW WITHOUT SPENDING ON MARKETING"}
                  </h1>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xzgd7
                    )}
                  >
                    {"Risk-Free Marketing: Agencies Invest in your success!"}
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.a__5uU4L,
                      sty.link__u5Kgr
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    <Icon13Icon
                      className={classNames(projectcss.all, sty.svg__teGuP)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pKzin
                      )}
                    >
                      {"Get in touch"}
                    </div>
                    <Icon13Icon
                      className={classNames(projectcss.all, sty.svg__j0PeT)}
                      role={"img"}
                    />
                  </PlasmicLink__>
                  <LoginButton
                    className={classNames(
                      "__wab_instance",
                      sty.loginButton__teOC
                    )}
                    link={`/c-landing-page-contact`}
                    shape={"rounded"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pIIhM
                      )}
                    >
                      {"Get in wait list"}
                    </div>
                  </LoginButton>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___2O4I)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___7Edu2)}
                >
                  <ChevronDown2Icon
                    className={classNames(projectcss.all, sty.svg__vk1Jv)}
                    role={"img"}
                  />
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___62Z7B)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img___62LO2)}
              displayHeight={"400px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/ez_marketing_platform_sacanagem/images/pexelsAmardeepSingh6327356829771Jpg.jpg",
                fullWidth: 4032,
                fullHeight: 3024,
                aspectRatio: undefined
              }}
            />
          </div>
          <div
            data-plasmic-name={"subtituloEProblema"}
            data-plasmic-override={overrides.subtituloEProblema}
            className={classNames(projectcss.all, sty.subtituloEProblema)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__jLrkk)}>
              <div
                data-plasmic-name={"subtitulo"}
                data-plasmic-override={overrides.subtitulo}
                className={classNames(projectcss.all, sty.subtitulo)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dfdbi
                  )}
                >
                  {"WHAT IS EZ MARKETING?"}
                </div>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.h2__5uU4L,
                    projectcss.__wab_text,
                    sty.h2__plhI5
                  )}
                >
                  {
                    "EZ MARKETING CONNECTS COMPANIES TO MARKETING AGENCIES THAT INVEST IN THEIR GROWTH"
                  }
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iNiE
                  )}
                >
                  {
                    "EZ Marketing is a disruptive platform that aims to transform the digital marketing landscape. Our goal is to centralize, measure and optimize marketing investments, meeting the needs of companies and professionals who face historical challenges in the sector. The platform guarantees secure payment for the service"
                  }
                </div>
              </div>
              <div
                data-plasmic-name={"problem2"}
                data-plasmic-override={overrides.problem2}
                className={classNames(projectcss.all, sty.problem2)}
              >
                <div
                  data-plasmic-name={"title"}
                  data-plasmic-override={overrides.title}
                  className={classNames(projectcss.all, sty.title)}
                >
                  <h3
                    data-plasmic-name={"h3"}
                    data-plasmic-override={overrides.h3}
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.h3__5uU4L,
                      projectcss.__wab_text,
                      sty.h3
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "The problem:"
                      : "THE PROBLEM:"}
                  </h3>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__w8Cxb
                    )}
                  >
                    {
                      "Marketing is Increasingly Expensive, the digital marketing market needs a solution that brings transparency, reliability and efficiency to all parties involved."
                    }
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__lcMOl)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__lsjEk)}
                  >
                    <_47SvgIcon
                      className={classNames(projectcss.all, sty.svg__tWaYy)}
                      role={"img"}
                    />

                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.h5__5uU4L,
                        projectcss.__wab_text,
                        sty.h5__p7Xav
                      )}
                    >
                      {"47%"}
                    </h5>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.h5__5uU4L,
                        projectcss.__wab_text,
                        sty.h5__ubya5
                      )}
                    >
                      {"Ad budgets wasted"}
                    </h5>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.h5__5uU4L,
                        projectcss.__wab_text,
                        sty.h5__ygodl
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>
                          {
                            "47% of marketing budgets are wasted on ineffective campaigns.\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span plasmic_default__span__5uU4L"
                          }
                          style={{
                            fontWeight: 300,
                            color: "var(--token-P8WwsjeDoj7s)"
                          }}
                        >
                          {"Gartner Ma"}
                        </span>
                        <React.Fragment>{""}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span plasmic_default__span__5uU4L"
                          }
                          style={{
                            fontWeight: 200,
                            color: "var(--token-P8WwsjeDoj7s)"
                          }}
                        >
                          {"rketing Data 2023"}
                        </span>
                      </React.Fragment>
                    </h5>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mgoEn)}
                  >
                    <_62SvgIcon
                      className={classNames(projectcss.all, sty.svg__cgAt8)}
                      role={"img"}
                    />

                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.h5__5uU4L,
                        projectcss.__wab_text,
                        sty.h5__qozpO
                      )}
                    >
                      {"62%"}
                    </h5>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.h5__5uU4L,
                        projectcss.__wab_text,
                        sty.h5__om20
                      )}
                    >
                      {"Oversold promises"}
                    </h5>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.h5__5uU4L,
                        projectcss.__wab_text,
                        sty.h5__aRTe
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>
                          {
                            "62% of agencies admit to overselling results just to close deals.\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span plasmic_default__span__5uU4L"
                          }
                          style={{
                            fontWeight: 300,
                            color: "var(--token-P8WwsjeDoj7s)"
                          }}
                        >
                          {"HubSpot Agency Survey 2022"}
                        </span>
                      </React.Fragment>
                    </h5>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__eLSyt)}
                  >
                    <_74SvgIcon
                      className={classNames(projectcss.all, sty.svg__wWrth)}
                      role={"img"}
                    />

                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.h5__5uU4L,
                        projectcss.__wab_text,
                        sty.h5__ay974
                      )}
                    >
                      {"74%"}
                    </h5>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.h5__5uU4L,
                        projectcss.__wab_text,
                        sty.h5__tlSAq
                      )}
                    >
                      {"No marketing budget"}
                    </h5>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.h5__5uU4L,
                        projectcss.__wab_text,
                        sty.h5___44HZy
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>
                          {
                            "74% of small businesses don\u2019t have budget for professional marketing.\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span plasmic_default__span__5uU4L"
                          }
                          style={{
                            fontWeight: 200,
                            color: "var(--token-P8WwsjeDoj7s)"
                          }}
                        >
                          {"SBA (Small Business Administration) 2023"}
                        </span>
                      </React.Fragment>
                    </h5>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"solucao"}
            data-plasmic-override={overrides.solucao}
            className={classNames(projectcss.all, sty.solucao)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__mzhtU)}>
              <div
                data-plasmic-name={"foreground2"}
                data-plasmic-override={overrides.foreground2}
                className={classNames(projectcss.all, sty.foreground2)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.h2__5uU4L,
                    projectcss.__wab_text,
                    sty.h2__v9Rp1
                  )}
                >
                  {"THE SOLUTION:\nAGENCIES INVEST IN YOU"}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bpBh9
                  )}
                >
                  {
                    "By combining market analysis tools, competitor differentiation, price dynamics management and continuous feedback, in addition to the best portfolio made to showcase the work of marketing agencies, the platform positions itself as the first system that offers a unified and detailed view of each company's performance in relation to its potential."
                  }
                </div>
              </div>
              <div
                data-plasmic-name={"vantagens"}
                data-plasmic-override={overrides.vantagens}
                className={classNames(projectcss.all, sty.vantagens)}
              >
                <div className={classNames(projectcss.all, sty.column__mb5W4)}>
                  <ListingListBox
                    className={classNames(
                      "__wab_instance",
                      sty.listingListBox__iG0H1
                    )}
                    slot={
                      <React.Fragment>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___85XPm
                          )}
                        >
                          <MoneySvgrepoComSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__kQu4D
                            )}
                            role={"img"}
                          />
                        </div>
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.h4__5uU4L,
                            projectcss.__wab_text,
                            sty.h4__xuNel
                          )}
                        >
                          {"No financial risk"}
                        </h4>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__wIzDr
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__oNo3B
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___7O3Yf
                              )}
                            >
                              {"Agencies invest like VC investors."}
                            </div>
                          </div>
                        </div>
                      </React.Fragment>
                    }
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__c72IJ)}
                      displayHeight={"250px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/ez_marketing_platform_sacanagem/images/pexelsNicolaBarts7927581Jpg.jpg",
                        fullWidth: 6000,
                        fullHeight: 4000,
                        aspectRatio: undefined
                      }}
                    />
                  </ListingListBox>
                </div>
                <div className={classNames(projectcss.all, sty.column__ahyRy)}>
                  <ListingListBox
                    className={classNames(
                      "__wab_instance",
                      sty.listingListBox__drPf2
                    )}
                    slot={
                      <React.Fragment>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__xnOxm
                          )}
                        >
                          <TrophySportsAndCompetitionSvgrepoComSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___9Jc9X
                            )}
                            role={"img"}
                          />
                        </div>
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.h4__5uU4L,
                            projectcss.__wab_text,
                            sty.h4__yjQj
                          )}
                        >
                          {"Competition in your favor"}
                        </h4>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___2Hszg
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__asjz2
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ewEb
                              )}
                            >
                              {"Different agencies compete for your growth."}
                            </div>
                          </div>
                        </div>
                      </React.Fragment>
                    }
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__oYgGw)}
                      displayHeight={"250px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/ez_marketing_platform_sacanagem/images/pexelsPixabay34514Jpg.jpg",
                        fullWidth: 7197,
                        fullHeight: 4803,
                        aspectRatio: undefined
                      }}
                    />
                  </ListingListBox>
                </div>
                <div className={classNames(projectcss.all, sty.column__lwKOq)}>
                  <ListingListBox
                    className={classNames(
                      "__wab_instance",
                      sty.listingListBox___4L3Ky
                    )}
                    slot={
                      <React.Fragment>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__vicSl
                          )}
                        >
                          <ReportSvgrepoComSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__lVtuU
                            )}
                            role={"img"}
                          />
                        </div>
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.h4__5uU4L,
                            projectcss.__wab_text,
                            sty.h4__r8EzD
                          )}
                        >
                          {"Full monitoring"}
                        </h4>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__x3JR5
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__gj62L
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__sihtr
                              )}
                            >
                              {
                                "From CONVERSION TO PAYMENT CONFIRMATION, all within the platform."
                              }
                            </div>
                          </div>
                        </div>
                      </React.Fragment>
                    }
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__abv3J)}
                      displayHeight={"250px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/ez_marketing_platform_sacanagem/images/pexelsShkrabaanthony5816299Jpg.jpg",
                        fullWidth: 4000,
                        fullHeight: 6000,
                        aspectRatio: undefined
                      }}
                    />
                  </ListingListBox>
                </div>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"provaSocial"}
            data-plasmic-override={overrides.provaSocial}
            className={classNames(projectcss.all, sty.provaSocial)}
          >
            <div className={classNames(projectcss.all, sty.freeBox___2GNef)}>
              <div className={classNames(projectcss.all, sty.freeBox__s9H2Z)}>
                <div
                  data-plasmic-name={"left2"}
                  data-plasmic-override={overrides.left2}
                  className={classNames(projectcss.all, sty.left2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gnorW
                    )}
                  >
                    {"Join over 200+ businesses already on the waitlist."}
                  </div>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.h2__5uU4L,
                      projectcss.__wab_text,
                      sty.h2__rKo5P
                    )}
                  >
                    {
                      '"If you\'re not an expert, outsource it to those who are."'
                    }
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uVuFd
                    )}
                  >
                    {"-Gary Vaynerchuk"}
                  </div>
                  <LoginButton
                    className={classNames(
                      "__wab_instance",
                      sty.loginButton__loTPc
                    )}
                    link={`/c-landing-page-contact`}
                    shape={"rounded"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qfBbA
                      )}
                    >
                      {"Get in wait list"}
                    </div>
                  </LoginButton>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.a__5uU4L,
                      sty.link__u6Gq8
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <Icon13Icon
                        className={classNames(projectcss.all, sty.svg__yF6RE)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rut3R
                      )}
                    >
                      {"Connect"}
                    </div>
                    {false ? (
                      <Icon13Icon
                        className={classNames(projectcss.all, sty.svg__fMmfx)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__fyU6F)}>
            <div className={classNames(projectcss.all, sty.freeBox__daKGr)} />

            <div className={classNames(projectcss.all, sty.freeBox__hWwIp)}>
              <div className={classNames(projectcss.all, sty.freeBox__oFotb)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sH6Nu
                  )}
                >
                  {"Let's get going"}
                </div>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.h2__5uU4L,
                    projectcss.__wab_text,
                    sty.h2__bR7UY
                  )}
                >
                  {"Secure Your Place on the Waiting List!"}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__o44KE
                  )}
                >
                  {
                    "Be one of the first companies to access this revolution in digital marketing.\r"
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__lsI8T)}>
                <Button4
                  data-plasmic-name={"button4"}
                  data-plasmic-override={overrides.button4}
                  className={classNames("__wab_instance", sty.button4)}
                  color={"neutral"}
                  end={
                    <Icon15Icon
                      className={classNames(projectcss.all, sty.svg__uUtpy)}
                      role={"img"}
                    />
                  }
                  iconEnd={true}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kZ9BS
                      )}
                    >
                      {"Submit now"}
                    </div>
                  }
                  linkTo={`/c-landing-page-contact`}
                  size={"large"}
                  start={
                    <CircleIcon
                      className={classNames(projectcss.all, sty.svg__umFVa)}
                      role={"img"}
                    />
                  }
                />

                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.a__5uU4L,
                    projectcss.__wab_text,
                    sty.link__yWqj
                  )}
                  component={Link}
                  href={"https://www.foundersbase.com/startup/239"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {"Learn more..."}
                </PlasmicLink__>
              </div>
            </div>
          </div>
          <FooterSection
            data-plasmic-name={"footerSection"}
            data-plasmic-override={overrides.footerSection}
            className={classNames("__wab_instance", sty.footerSection)}
          />

          <Embed
            data-plasmic-name={"metaPixel"}
            data-plasmic-override={overrides.metaPixel}
            className={classNames("__wab_instance", sty.metaPixel)}
            code={
              "<!-- Meta Pixel Code -->\r\n<script>\r\n!function(f,b,e,v,n,t,s)\r\n{if(f.fbq)return;n=f.fbq=function(){n.callMethod?\r\nn.callMethod.apply(n,arguments):n.queue.push(arguments)};\r\nif(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';\r\nn.queue=[];t=b.createElement(e);t.async=!0;\r\nt.src=v;s=b.getElementsByTagName(e)[0];\r\ns.parentNode.insertBefore(t,s)}(window, document,'script',\r\n'https://connect.facebook.net/en_US/fbevents.js');\r\nfbq('init', '294590235435738');\r\nfbq('track', 'PageView');\r\n</script>\r\n<noscript><img height=\"1\" width=\"1\" style=\"display:none\"\r\nsrc=\"https://www.facebook.com/tr?id=294590235435738&ev=PageView&noscript=1\"\r\n/></noscript>\r\n<!-- End Meta Pixel Code -->\r\n\r\n"
            }
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "cabecalho",
    "h1",
    "subtituloEProblema",
    "subtitulo",
    "problem2",
    "title",
    "h3",
    "solucao",
    "foreground2",
    "vantagens",
    "provaSocial",
    "left2",
    "button4",
    "footerSection",
    "metaPixel"
  ],
  cabecalho: ["cabecalho", "h1"],
  h1: ["h1"],
  subtituloEProblema: [
    "subtituloEProblema",
    "subtitulo",
    "problem2",
    "title",
    "h3"
  ],
  subtitulo: ["subtitulo"],
  problem2: ["problem2", "title", "h3"],
  title: ["title", "h3"],
  h3: ["h3"],
  solucao: ["solucao", "foreground2", "vantagens"],
  foreground2: ["foreground2"],
  vantagens: ["vantagens"],
  provaSocial: ["provaSocial", "left2"],
  left2: ["left2"],
  button4: ["button4"],
  footerSection: ["footerSection"],
  metaPixel: ["metaPixel"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  cabecalho: "div";
  h1: "h1";
  subtituloEProblema: "div";
  subtitulo: "div";
  problem2: "div";
  title: "div";
  h3: "h3";
  solucao: "div";
  foreground2: "div";
  vantagens: "div";
  provaSocial: "div";
  left2: "div";
  button4: typeof Button4;
  footerSection: typeof FooterSection;
  metaPixel: typeof Embed;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCLandingPage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCLandingPage__VariantsArgs;
    args?: PlasmicCLandingPage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicCLandingPage__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicCLandingPage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCLandingPage__ArgProps,
          internalVariantPropNames: PlasmicCLandingPage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCLandingPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCLandingPage";
  } else {
    func.displayName = `PlasmicCLandingPage.${nodeName}`;
  }
  return func;
}

export const PlasmicCLandingPage = Object.assign(
  // Top-level PlasmicCLandingPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    cabecalho: makeNodeComponent("cabecalho"),
    h1: makeNodeComponent("h1"),
    subtituloEProblema: makeNodeComponent("subtituloEProblema"),
    subtitulo: makeNodeComponent("subtitulo"),
    problem2: makeNodeComponent("problem2"),
    title: makeNodeComponent("title"),
    h3: makeNodeComponent("h3"),
    solucao: makeNodeComponent("solucao"),
    foreground2: makeNodeComponent("foreground2"),
    vantagens: makeNodeComponent("vantagens"),
    provaSocial: makeNodeComponent("provaSocial"),
    left2: makeNodeComponent("left2"),
    button4: makeNodeComponent("button4"),
    footerSection: makeNodeComponent("footerSection"),
    metaPixel: makeNodeComponent("metaPixel"),

    // Metadata about props expected for PlasmicCLandingPage
    internalVariantProps: PlasmicCLandingPage__VariantProps,
    internalArgProps: PlasmicCLandingPage__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/c-landing-page",
      pagePath: "/c-landing-page",
      params: {},
      query: {}
    })
  }
);

export default PlasmicCLandingPage;
/* prettier-ignore-end */
